### ISSUE TITLE
AIA, OCSP Responder certificates, and the Root CA?

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#102]
Breakout of question from #86 

For the AIA artifacts in OCSP responder _certificates_: 

- For the Root CA and OCSP responder, what is the AIA value used? Not present or ?? (circular logic)
- If the Root has a cross-cert for purposes of trust store inclusion, what is the AIA value used?

**Comment by techliaison** [comment]
Root certificates do NOT contain AIA (they do not need the pointer to issuer certs as the path stops at the self-signed root cert & you can't revoke a self-signed root cert so no need to point to an OCSP responder)
Cross-certificates even when issued to a CA that also has a self-signed certificate is NOT used as a root certificate - the cross-cert does have an AIA so the RP can find the path to the CA that signed the cross-cert.

OCSP responder certs should probably have an AIA so the cert itself can be validated.  But the AIA would not contain the OCSP option, just the CAIssuers

**Comment by mttcpr2** [comment]
It is common practice to include the AIA-caIssuers in the responder cert, though, you shouldn't need it in the delegated model because you already have the issuing CA cert in hand (and presumably an entire cert path) before you send the OCSP request.
