### ISSUE TITLE
5.3 Personnel controls

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#122]
- 5.3.1 Qualifications, experience, and clearance requirements
- 5.3.2 Background check procedures
- 5.3.3 Training Requirements and Procedures
- 5.3.4 Retraining frequency and requirements
- 5.3.5 Job rotation frequency and sequence
- 5.3.6 Sanctions for unauthorized actions
- 5.3.7 Independent Contractor Controls
- 5.3.8 Documentation supplied to personnel

Which government (USG) requirements do we want to include?  

- At a minimum, 5.3.1 and 5.3.2 should include the US designation (US citizen or other appropriate wording?)
- Investigation requirements and clearance requirements

**Comment by jaspenc** [comment]
Again, I'd start with Common CP language here.  Not only do you want trustworthy, knowledgeable individuals, but you need to be sure they stay abreast of changes to the infrastructure - new requirements etc.

**Comment by lachellel** [comment]
#136
