### ISSUE TITLE
2.2 - Test Websites

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#123]
Instead of each issuer hosting a test website, would it be more efficient if we centralized it into one website that included audit and other public trust information?

**Comment by lachellel** [comment]
Yes, it could be. 

Is policy impacted? Or simply an architecture and deployment decision?  If no policy, I'm going to mark for the working group.

**Comment by lachellel** [comment]
Closing - won't impact policy; will impact design and operations!
