### ISSUE TITLE
Section 3.2.2.4.11: Domain validation - Other Methods 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#128]
Ballot 180 and 181: 

- https://cabforum.org/2017/01/07/ballot-181-readopting-br-3-2-2-4-part-1/

Addition of: 

**3.2.2.4.11 Other Methods**
The CA SHALL confirm that, as of the date the Certificate issues, either the CA or a Delegated Third Party has validated each Fully-Qualified Domain Name (FQDN) listed in the Certificate by using any method of confirmation, provided that the CA maintains documented evidence that the method of confirmation establishes that the Applicant is the Domain Name Registrant or has control over the Fully Qualified Domain Name (FQDN).

**Comment by lachellel** [comment]
#93

**Comment by lachellel** [comment]
Other Methods is wide open - 

- What is the purpose of Other Methods and how could it apply to US govt and DotGov and DotMil?
- What are thoughts?  
- We need consistency, accountability and audit.

**Comment by techliaison** [comment]
Please don't rely on the "Other Methods" unless we are going to define a very specific one for use withing the government.
There is a ballot under discussion within CABForum now to drop 3.2.2.4.11 Other Methods and to require that CAs keep a record of which of the 10 validation methods is used for each certificate issued.  The discussion is centered around whether this "record" must actually be carried in an extension of the certificate or just be available for an audit.

**Comment by lachellel** [comment]
Agree - that's definitely why we wanted to open the Issue, discuss, and track.  We need specifics.

**Comment by lachellel** [comment]
Remove 3.2.2.4.11 Other Methods

- "Not allowed under this policy"


Ref:  **Mozilla** Trust store policy
