### ISSUE TITLE
Section 5.3.3  (Personnel Controls) Training Requirements and Procedures

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#139]
CAB Forum introduces a new "role" here:  "Validation Specialist".  This seems to approximate the "Officer" Role in our lexicon.  While Validation Specialist is defined in Section 1.6 as "Someone who performs the information verification duties specified by these Requirements," it is not called out as one of the Trusted Roles and is not mentioned anywhere else in the CABForum CP except Section 8.7 Self Audits where it states: "the CA SHALL strictly control the service quality of Certificates issued or containing information verified by a Delegated Third Party by having a Validation Specialist employed by the CA perform ongoing quarterly audits against a randomly selected sample of at least the greater of one certificate or three percent of the Certificates verified by the Delegated Third Party in the period beginning immediately after the last sample was taken."  And in that context it sounds more like the Internal Auditor trusted role.  
Do we add a "Validation Specialist" Trusted Role?  Combine the Validation Specialist duties with the Officer Trusted Role and/or Auditor Trusted Role?

**Comment by lachellel** [comment]
Discussion: 

- Combine Validation Specialist with Officer role via definitions (?)
- What do we do about Delegated Third Party overall?  Are DTP going to even be allowed? Section 1.3.2
  - Remove DTP
