### ISSUE TITLE
Section 6.1.2 Subscriber key pairs and FIPS 140

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#141]
Discussion topic raised by operations: 

- Section 6.1.2
- We added the FIPS 140 designation

> Subscribers SHALL generate their own keys in FIPS 140 validated cryptographic modules, in compliance with sections 6.1.5 and 6.1.6.

Question(s): 
-  How does the CA **know** whether the device used a FIPS 140 crypto module?
-  How does this get audited? 
-  Is this too specific for device TLS key pairs and it should be inherited from govt wide policies instead?  It is an auditable item.

**Comment by rmhrisk** [comment]
Without:
1a) generation of keys for the users
1b) tokens supporting a remote attestation model

It is not possible to know for sure, absent those things your choices are:
2a) Ask user to pinky swear in a subscriber agreement,
2b) Only issue certificates when the CSR contains an unverifiable claim that a given implementation was used to generate the keys (still roughly a pinky swear)
2c) Only issue certificates you created the CSR you generated and look for the unverifiable claim in the CSR (again still roughly a pinky swear)

Auditing with any reasonable level of assurance without 1a or 1b is basically impossible.

**Comment by lachellel** [comment]
My opinion = +1 @rmhrisk 

- Ditto the comments for Section 6.2.1 + Subscribers and FIPS 140 Level 1
- Since this is an auditable event, are there other controls for govt systems + these controls will supersede a Certificate Policy for the CAs in all cases?
  - RE: Risk Management Framework
