### ISSUE TITLE
Alignment of Certificate Profiles 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#144]
Question(s) for certificate profiles + Section 7 scrub: 

- For the certificate profiles [here](https://github.com/uspki/policies/blob/master/certificate-profiles.md)
- Differing terminology is used between human readable versus x509 specific -> for example, Digital Signature versus digitalSignature
- **Question 1:**  Which do we want?  +1 for consistency 

- There was a note to align all certificate profiles to contain the same tables and all elements / extensions (an outer join across the profiles)
- If a profile would never have the extension, simply mark as "Not Allowed"
- **Question 2:** Continue with aligning all profiles?

**Comment by lachellel** [comment]
@mttcpr @techliaison @larryfrank

thoughts?

**Comment by LarryFrank** [comment]
> human readable versus x509 specific 
I have always preferred to distinguish between actual attribute values (e.g., certificates that have a Key Usage of digitalSignature) and discussing when something is used (e.g. when used for digital signature).  But it isn't always clear - possibly easiest to just go with the X.509.

> Align profiles

I think it is  a mistake to put profiles into the policy but I guess that ship has sailed.  Having a consistent set of fields makes sense to me.

**Comment by techliaison** [comment]
I would prefer to use the ASN.1 name (eg. digitalSignature, subjectKeyIdentifier), but I am probably the one who introduced the mixed use in the profiles as written.

I agree align the profiles and be consistent

I thought we had also agreed that making the profiles a separate file or at least an appendix that might be more easily updated was a good idea.

**Comment by LarryFrank** [comment]
Sorry - I may have mis-understood the question... To be clear - for attribute values in the profiles - I would recommend that it should always be the ANS.1.
