### ISSUE TITLE
30 days maximum lifetime for secrets

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#148]
see comments and discussions here: https://github.com/uspki/policies/pull/137

Applies to random values, shared secrets examples, including the domain validation methods: 
- https://github.com/uspki/policies/blob/master/certificate-policy.md#32246-agreed-upon-change-to-website

Add clarifying language to Section 4 lifecycle

**Comment by LarryFrank** [comment]
> 30 days

Sorry - I was reading through SP 800-63-3A.  Had not noticed this before...  It says:
"b. The CSP MAY provide an enrollment code directly to the subscriber if binding to an authenticator will occur at a later time.
c. The enrollment code SHALL be valid for a maximum of 7 days."
I think we are talking about the same thing and need to adjust the "30 days" in the policy to 7 (and probably change Common, FBCA and other Federal CPs to reflect the updated requirement from NIST...

**Comment by LarryFrank** [comment]
there is more... do we care?
Enrollment codes sent to a postal address of record SHALL be valid for a maximum of 10 days but MAY be made valid up to 30 days via an exception process to accommodate addresses outside the contiguous United States. Enrollment codes sent by telephone SHALL be valid for a maximum of 10 minutes. Enrollment codes sent via email SHALL be valid for a maximum of 24 hours.

**Comment by lachellel** [comment]
Limitations, Section 2.3 of part A: 

> Additionally, this revision of these guidelines does not explicitly address device identity, often referred to as machine-to-machine (such as router-to-router) authentication or interconnected devices, commonly referred to as the internet of things (IoT). That said, these guidelines are written to refer to generic subjects wherever possible to leave open the possibility for applicability to devices


We **can** apply if we agree but not explicitly required - lets look at it from a risk perspective first.   

As for the other CPs, yes, we do have to apply for human subscriber identity and authentication.

**Comment by LarryFrank** [comment]
Agree - forgot 800-63 only applies to people...
