### ISSUE TITLE
Section 2 basic edits

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#15]
See PR #14 

Included: 

- Section 2 (top)
- Section 2.2 - did not specify "where" the CP would be posted yet
- Section 2.3 - partial

Did **not** include _Section 2.4 Access Controls on Repositories_ edits.   <-- worthy of discussion!

**Comment by lachellel** [comment]
@konklone @weirdscience @techliaison @tkpk @LarryFrank

See issue and pull request referenced

**Comment by LarryFrank** [comment]
2.4 - Common text (modified here) would be a good start...

The CA shall protect information not intended for public dissemination or modification. CP, Redacted CPS, CA certificates and CRLs shall be publicly available through the Internet. Direct and/or remote access to other information in the CA repositories shall be determined by agencies pursuant to their authorizing and controlling statutes.

**Comment by LarryFrank** [comment]
On Section 2.2 statement above.  Typically, we leave it to the CA CPS to identify the repository but if it is known where the CP, CPS, etc. will be posted and it won't likely change - could put the in a URL in the policy.

**Comment by techliaison** [comment]
Since the CP is supposed to cover both root and issuing CAs and issuing CAs can change over time, we need to leave the location of the repositories open as each issuing CA is likely to have their own CPS which will be different from the root CAs CPS

**Comment by grandamp** [comment]
+1  I was hoping to see only one CP, and each issuing CA would be
responsible of producing it's own _public_ CPS which describe _how_ they
adhere to the CP.

Will there be a central location for all?  Or, is each issuer responsible
for their own repository?  Is this the _official_ repo for the CP?

**Comment by tkpk** [comment]
@grandamp I would expect that the official repo for the CP would continue to be idmanagement.gov, which would also be the location for CPSs for CAs operated by the FPKI.  

CPSs for CAs operated by other entities would be published at the public location of their choice.

**Comment by konklone** [comment]
Totally up to the team, but I would expect that we make a new subdomain for this root, so as to avoid any confusion with the FICAM/ID side of the FPKI (this root isn't managing IDs), and so that any changes made on GitHub get automatically reflected in the official version (which isn't a feature offered by idmanagement.gov right now). 

We're using https://https.cio.gov/uspki/certificate-policy/ as a temporary location, but [Federalist](https://federalist.18f.gov) (which also syncs with GitHub) may make a good operational home for the documents.

**Comment by lachellel** [comment]
addressed in an additional commit to #147

**Comment by lachellel** [comment]
closing
