### ISSUE TITLE
Certificate Profiles: Private Key Usage Period

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#153]
Suggest removing private key usage period as "optional" in the server authentication and the subordinate CA certificate profile. 

- How often is it used / enforced? _Generally_ deprecated for usage?
- We removed reissuances as an option for lifecycle

**Comment by grandamp** [comment]
yes please!

**Comment by LarryFrank** [comment]
As we currently have it, private key usage period = certificate life as we currently have it set up except for OCSP (no renewal).  Redundant and not helpful.  Agree with remove and close.

**Comment by lachellel** [comment]
[Consolidated from comments received via email.]

**Organization / Program:** DoD
**Section:** Certificate Profiles - General
**Comments:**
Private Key Usage Period
This is not a RFC 5280 extension.  It should not be used.  This comment applies to multiple profiles.

**Comment by lachellel** [comment]
https://github.com/uspki/policies/commit/308aaf39b583c513aa576c6677ad7e78b26bb778

**Comment by lachellel** [comment]
closed by #476
