### ISSUE TITLE
3.2.5 Validation of authority

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#154]
The policy requirements in Section 3.2.5 can be confusing or misconstrued in the scope of this CP.  For example, the use of "organization". 

Appreciate any / all suggestions for updates that add clarity. 

> ### 3.2.5 Validation of authority
> If the Applicant for a Certificate containing Subject Identity Information is an organization, the CA SHALL use a Reliable Method of Communication to verify the authenticity of the Applicant Representative's certificate request.
> 
> The CA MAY use the sources listed in section 3.2.2.1 to verify the Reliable Method of Communication. Provided that the CA uses a Reliable Method of Communication, the CA MAY establish the authenticity of the certificate request directly with the Applicant Representative or with an authoritative source within the Applicant's organization, such as the Applicant's main business offices,  human resource offices, information technology offices, or other division that the CA deems appropriate.
> 
> In addition, the CA SHALL establish a process that allows an Applicant to specify the individuals who may request Certificates. If an Applicant specifies, in writing, the individuals who may request a Certificate, then the CA SHALL NOT accept any certificate requests that are outside this specification. The CA SHALL provide an Applicant with a list of its authorized certificate requesters upon the Applicant's verified written request.

@techliaison @LarryFrank

**Comment by LarryFrank** [comment]
Not sure it needs further clarification as it provides a sufficient framework for CPS language to address. For "organization" - I think the CA/B forum intent is the "organization" specified in the DN of the certificate.  I.E., a person authorized by the "US Government" to request a certificate on behalf of the applicant.  DoD uses two methods - either the person is issued a DoD PKI medium-hardware certificate that contains a specific policy OID that requires that the person be vetted as authorized to request NPE certificates or an RA, at of before the time of the issuance request, vets the person's authority to request certificates.  Both verifications are done using direct communication with the part of the organization that the person represents (e.g., USAF) - typically, the RA is part of that agency.

**Comment by lachellel** [comment]
This might be OBE as I'm not sure we are using the current RA procedures and are focusing on technical controls.  

This section is very confusing too (mea culpa) and  I'm rewriting to align with Authorizing Authority (domain owners).
