### ISSUE TITLE
section 2 edits

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#16]
I suggest we only accept RFC 3647 format and not 2527 as well

**Comment by lachellel** [comment]
Makes sense - I have the 2527 as a ~~strikethrough~~ 
as in ~~RFC 2527~~
- So everyone could see _that_ particular change from the draft doc when it renders 

I tried to do this ~~strikethrough~~ method when there were minor words in a sentence, but those words hold major meaning; to show the edits. 

We can grep out the ~~strikethrough~~ after comments and agreement?
