### ISSUE TITLE
all AIA URLs in Subordinate CA certs should be publicly accessible

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#169]
In 7.1.2.2 c change "At least one instance" to "All instances"
Having one or more URLs in public certificates not be resolvable can create timing issues for RP applications trying to do dynamic path discovery & validation

**Comment by lachellel** [comment]
- Added to the certificate profiles (and removed most of Section 7.1.2.x text). 
- Added was the "All instances". 

+1
