### ISSUE TITLE
Names of CAs operating under the policy.

### ISSUE THREAD

**Issue by LarryFrank** [uspki/policies#170]
Section 1.1 last part has "The following Certification Authorities are covered under this CP:" followed by a table.  Recommend deleting the text and the table - as this would require the CP to be changed each time a CA is stood up.  I do not believe this required by CA/B standards (I looked at a couple of publically trusted commercial policies and they don't have this).

**Comment by lachellel** [comment]
Duplicate. 

Removed from CP in #475 
Closing!
