### ISSUE TITLE
authentication for revocation request

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#173]
Rather than "no stipulation" for identification and authentication for revocation requests I would think the request for revocation to be honored should either come from an authorized representative of the subscriber's organization or somehow be associated with the cert - like using the private key - otherwise it must be authenticated as official, unless the request is due to suspected compromise of the key.  
at a minimum I would expect a reference to 4.9.

**Comment by lachellel** [comment]
I think this one was addressed?
