### ISSUE TITLE
Key changeover

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#179]
We probably want to prohibit doing a key rollover and instead require standing up a new CA each time the key needs to be changed.
Microsoft has this restriction in their trust store policy:

Private Keys and subject names must be unique per root certificate; reuse of private keys or subject names in subsequent root certificates by the same CA may result in random certificate chaining issues. CAs must generate a new key and apply a new subject name when generating a new root certificate prior to distribution by Microsoft.

**Comment by lachellel** [comment]
I think we addressed this in the edits (no rekeys, no renewals) - please confirm and reopen the issue if the topic hasn't been addressed adequately!
