### ISSUE TITLE
lines 1465-1470 (5.7.1)

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#180]
"The FPKIPA shall notify the CA, in writing, of its intentions in response to the security incident seven (7) days prior to the action by the FPKIPA except under exceptional circumstances (as defined in the glossary) where the FPKIPA will make reasonable efforts to communicate with the CA prior to taking action. The CA may propose an alternate course of action and the FPKIPA may consider reasonable alternatives but reserves the right to reject any proposed course of action not in the government’s best interest."

Need to clarify what intentions in the above text.
are we saying the CA will be given 7 days warning before the PA talks to affected parties or gives at least 7 days for the CA to find a 3rd party investigator?  Not all of the above bullets carry the same need for advance warning

also "exceptional circumstances" is not currently defined in the glossary.

**Comment by lachellel** [comment]
Section 5.7.1 requirements were updated for this comment and related comments.
