### ISSUE TITLE
5.7.3 Recovery Procedures after Key Compromise

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#181]
It seems backwards that if a CA private key is compromised we give the Root 7 days to revoke that compromised CA, but it is only given 24 hours to revoke all its subscriber certs.

Additionally the CP says it does not support renewal but here we say "Subscriber certificates may be renewed automatically by the CA under the new key pair, or the CA may require subscribers to repeat the initial certificate application process."
at a minimum change "renewed" to re-issued" but we should require revalidation depending on how and when the CA key was compromised so you are not re-issuing subscriber certs that may have been issued by that compromised key.

**Comment by lachellel** [comment]
> It seems backwards that if a CA private key is compromised we give the Root 7 days to revoke that compromised CA, but it is only given 24 hours to revoke all its subscriber certs

Related to #58  and this: 

![image](https://user-images.githubusercontent.com/6501821/31133207-cf943fd0-a82c-11e7-9f11-169edde8d0b6.png)

Discussed changing **both** to 24 hours (subordinate/issuing and subscriber).  Update all to 24 hours.

**Comment by lachellel** [comment]
> Additionally the CP says it does not support renewal but here we say "Subscriber certificates may be renewed automatically by the CA under the new key pair, or the CA may require subscribers to repeat the initial certificate application process." At a minimum change "renewed" to re-issued" but we should require revalidation depending on how and when the CA key was compromised so you are not re-issuing subscriber certs that may have been issued by that compromised key.

:+1:  - good catch.

**Comment by lachellel** [comment]
Clause for "Subscriber certificates may be renewed automatically by the CA under the new key pair, or the CA may require subscribers to repeat the initial certificate application process." removed.
