### ISSUE TITLE
5.8 CA or RA termination

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#182]
this section has what appears to be contradictory language or at least the order should be reviewed.

If a CA terminates before all the certificates have expired - the PA would need more than just the CA's signing keys to continue operating that CA until all certs were expired - at a minimum the database of issued certs as well as control of any URLs in the certificates would be required so certificate status information for any non-expired certs could be maintained.

Is this language meant to say the PA would be responsible for revoking all remaining certificates and issuing the last CRL prior to destroying the key?

**Comment by lachellel** [comment]
Updates to Section 5 addressed this comment.
