### ISSUE TITLE
Inconsistent requirements for subject name

### ISSUE THREAD

**Issue by dcooper16** [uspki/policies#193]
There is inconsistent information in the certificate policy and profile about the contents of the subject field in domain validated server authentication certificates.

The certificate profile says that the subject field contains "cn=<one domain name>," however, Section 3.1.3 of the CP says that the subject field also contains a countryName:
```
Subscribers are not identified in Domain Validation certificates. Only the country (US) and domain name is included in the subject information.
```
Meanwhile, Section 7.1.4.2.2 contains generic rules of "optional," "required if," "prohibited if," etc. If the  profile is correct, then it seems that Section 7.1.4.2.2 should just say that CN is mandatory for all certificates; "S=District of Columbia," "O=U.S. Government," and "c=US" are mandatory for OV certificates but prohibited for DV certificates; and all other attributes are prohibited.

Does the subject name need to be exactly as described in the profile or is some flexibility permitted?

Field or Extension | Domain Validation | Organization Validation
-- | -- | --
Subject Identity Information | cn=\<one domain name\> | cn=\<one domain name\>,S=District of Columbia,O=U.S.Government,c=US

**Comment by lachellel** [comment]
Spot on.   

- DV: needs to show with or without c=US.
- OV: No flexibility.  The purpose is to have a streamlined OV profile that can be automated through authoritative data sources.  Missions wanted the U.S. Government assertion and once we start asserting ANY value except for cn in the subject - the values have to be validated.  

For Section 7.1.4.2.2 and verbiage, we were trying to align with CA/B Requirements verbiage to reduce the "policy mapping" reviews and interpretations.  

Should we simply **remove** all attributes other than the Required and put in the blanket statement of "All others prohibited"?  It would make a cleaner, simpler CP.

**Comment by dcooper16** [comment]
So the table in the profile should be:

Field or Extension | Domain Validation | Organization Validation
-- | -- | --
Subject Identity Information | cn=\<one domain name\>[,c=US] | cn=\<one domain name\>,S=District of Columbia,O=U.S.Government,c=US

I understand the desire to copy the CA/B Requirements verbiage in order to make the mapping easier, but I think it's okay in this case to clearly state the requirement for each attribute, especially where the CA/B Requirements just says "optional." It seems no worse than saying "Required" for the commonName when the CA/B Requirements say "Deprecated (Discouraged, but not prohibited)."

I would be inclined to just delete all the attributes where the CP currently says "Prohibited." The final paragraph of Section 7.1.4.2.2 already says that all other attributes "SHALL NOT be included." Why call out a handful of attributes that are prohibited when there are so many other attributes that aren't mentioned that are also prohibited? However, leaving them in doesn't cause confusion, since they are clearly labeled as prohibited, and leaving them in does make the text in this CP align more closely with the text in the CA/B Requirements.

**Comment by lachellel** [comment]
Updated the certificate profiles for this comment. 
- Also removing most of the Section 7 text in favor of the profiles.  
- Shortened extensively.
