### ISSUE TITLE
RSA public key requirements

### ISSUE THREAD

**Issue by dcooper16** [uspki/policies#196]
There is text in two of the certificate profiles that says "modulus must be 2048, 3072, or 4096 bits, an odd integer, not the power of a prime, with no factors < 752. Public exponent e shall be an odd positive integer such that 2^16+1 < e < 2^256-1. (Source: Appendix A, CA/Browser Forum, Baseline Requirements with NIST FIPS 186-4 clause to be shall over should.)"

I think this should just say that "modulus must be 2048, 3072, or 4096 bits. Public exponent e shall be an odd positive integer such that 2^16+1 < e < 2^256-1."

The reference to Appendix A seems outdated. Older versions of the Baseline Requirements had appendices, but the current one doesn't and some of these requirements don't appear to come from FIPS 186-4.

The part about how the modulus must "not the power of a prime, with no factors < 752" seems better suited to Section 6.1.6 of the CP, as this text made no sense to me out of context. An RSA modulus needs to be the product of two very large prime numbers, so what does it mean to say "no factors < 752." It wasn't until I searched through the Baseline Requirements and then read Section 5.3.3 of SP 800-89 that a requirement for the CA to perform partial public key validation, which is totally unrelated to any requirements for _generating_ an RSA key pair.

So, I would suggest removing this text from the profile and then change the text in Section 6.1.6 of the policy to say "The CA SHALL perform partial public key validation as specified in Section 5.3.3 of NIST SP 800-89 to confirm that the modulus is an odd number, is not the power of a prime, and has no factors smaller than 752."

**Comment by gerv** [comment]
Also:

> odd positive integer such that 2^16+1 < e < 2^256-1

65537 is a common modulus, so surely:

> odd positive integer such that 2^16+1 <= e < 2^256-1.
> ------------------------------------------------^

Gerv

**Comment by dcooper16** [comment]
Yes @gerv, I missed that part. Actually it should be
> odd positive integer such that  2^16 < e < 2^256 (or 2^16+1 <= e <= 2^256-1).

**Comment by lachellel** [comment]
> So, I would suggest removing this text from the profile and then change the text in Section 6.1.6 of the policy to say "The CA SHALL perform partial public key validation as specified in Section 5.3.3 of NIST SP 800-89 to confirm that the modulus is an odd number, is not the power of a prime, and has no factors smaller than 752.

The suggested change was addressed in Sections 6 and 5.
