### ISSUE TITLE
How much to copy text from Baseline Requirements

### ISSUE THREAD

**Issue by dcooper16** [uspki/policies#197]
Some of the text in the CP is more complicated than it needs to be since the text was copied from the Baseline Requirements document rather than being tailored to this particular CP. This was done in order to make it easier to demonstrate that the CP meets the Baseline Requirements, but it may also make it more difficult CAs to demonstrate that their CPSs satisfy the CP. I looked at some of the CPs listed at https://wiki.mozilla.org/CA/Included_Certificates and the ones I saw did not seem to copy language from Baseline Requirements in the same way this CP does.

I noticed this issue particularly in Section 3.2.2. Section 3.2.2.3, rather than copying the language from the Baseline Requirements seems to try to explain how this CP satisfies the requirements of Section 3.2.2.3 of the Baseline Requirements. Other sections, however, are more difficult to read.

Section 3.2.2.1, for example, basically copies the text from the Baseline Requirements, but then includes a practice note, which seems to negate the text before it.

I would like to propose that rather than copying the Baseline Requirements text here, the CP should simply say that the CA's responsibility is to verify that the applicant is part of the U.S. Federal government, and that doing so is sufficient to determine that attributes such as "c=US," "o=U.S. Government," and "st=District of Columbia" are valid for the certificate.

**Comment by lachellel** [comment]
I reworked some sections in 3.2.2.x to attempt to address this comment!  thank you.
