### ISSUE TITLE
Testing out a new issue during this GitHub demo

### ISSUE THREAD

**Issue by konklone** [uspki/policies#21]
Nothing super substantive to discuss here.

**Comment by konklone** [comment]
Follow up comments as necessary.

**Comment by lachellel** [comment]
Test succeeded!

**Comment by lachellel** [comment]
To link to another comment or pull request

#15

**Comment by konklone** [comment]
> Test succeeded!

Thanks for ringing in!

**Comment by konklone** [comment]
If you link to an issue: #12 and etc.

**Comment by konklone** [comment]
Linking to a comment: https://github.com/uspki/policies/issues/18#issuecomment-258132964
