### ISSUE TITLE
Section 1.5.4 CPS Approval procedures

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#24]
Discuss CPS Approval Procedures

@LarryFrank

> having the compliance auditor do compliance analysis is too late. Need an approved CPS to stand up operation - audit happens (at best) just prior to commencing operation - at which time, it may be very expensive to fix thing. DoD has someone actually do a compliance analysis before the PMA approves the CPS - then the auditor checks against that.

**Comment by LarryFrank** [comment]
To be clear - the compliance auditor certainly would still need to be familiar with the CP and CPS and, if  he/she/they identified specific discrepancies, point them out as part of the audit findings.  

DoD CP text for section 1.5.4 is "The PMA shall commission a compliance analysis study culminating in a written report that provides a summary of areas in which the CPS may not or does not comply with this CP. The compliance analysis shall be performed by an independent party. The PMA shall resolve these discrepancies prior to approving the CPS. The CMA must have a PMA approved CPS and meet all CP/CPS requirements prior to commencing operations."  I doubt this CP will use the term CMA - would be changed to "CA" in this.

**Comment by lachellel** [comment]
Still need update this in #147
