### ISSUE TITLE
1.5 policy administration

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#25]
#1.5 and #1.5.1 appear contradictory to me.
Although I agree CABForum created the BRs and can modify them following their procedures the term "This certificate policy" should be referring to the CP being written and not the BRs - maybe modify 1.5 as follows:
This Certificate Policy is based on the Baseline Requirements (BR) for the Issuance and Management of Publicly-Trusted Certificates present criteria established by the CA/Browser Forum for use by Certification Authorities when issuing, maintaining, and revoking publicly-trusted Certificates. The BR may be revised from time to time, as appropriate, in accordance with procedures adopted by the CA/Browser Forum.

**Comment by lachellel** [comment]
@techliaison 

merged edit:  https://github.com/uspki/policies/blob/master/certificate-policy.md#15-policy-administration

Closing this issue based on the PR
