### ISSUE TITLE
acceptable and prohibited uses

### ISSUE THREAD

**Issue by techliaison** [uspki/policies#26]
#1.4.1 - primary goal for appropriate certificate use seems a bit too generic
“efficient and secure electronic communication” includes email, user authentication, digital signature, and various other uses of person certificates – we should narrow this down to appropriate uses for TLS certificates (and code signing, timestamp when they are added)

#1.4.2 - we should somehow specify what is out of scope - for example all "person certificate uses" like digitally signing documents, protection of email, person authentication, etc.

**Comment by lachellel** [comment]
merged edit: https://github.com/uspki/policies/blob/master/certificate-policy.md#142-prohibited-certificate-uses

closing issue
