### ISSUE TITLE
6.1.5 Key Sizes - Subordinate CA

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#29]
Needs to be updated to align with NIST SP 800-131A and FIPS 186-4 AND possibly larger key size for the intermediates. 

Currently in Section 6.1.5

(2) Subordinate CA Certificates

||Validity period beginning on or before 31 Dec 2010 and ending on or before 31 Dec 2013|Validity period beginning after 31 Dec 2010 or ending after 31 Dec 2013|
|---|---|---|
|Digest algorithm|SHA-1, SHA-256, SHA-384 or SHA-512|SHA-1\*, SHA-256, SHA-384 or SHA-512|
|Minimum RSA modulus size (bits)|1024|2048|
|ECC curve|NIST P-256, P-384, or P-521|NIST P-256, P-384, or P-521|
|Minimum DSA modulus and divisor size (bits)\*\*\*|L= 2048, N= 224 or  L= 2048, N= 256|L= 2048 N= 224 or L= 2048 N= 256

**Comment by lachellel** [comment]
1) Update Minimums and Validity Periods to be relevant

2) Are there any restrictions on the Intermediate / Issuing CA and key size?  _Besides the Minimum_ - what is the maximum?  Can it be 3072 or 4096?
>> According to NIST, 3072 and 4096 are allowed

**Comment by LarryFrank** [comment]
Suggest dropping the 2010-2013 column - as it is now (or should be) OBE.

> 2.Are there any restrictions on the Intermediate / Issuing CA and key size? Besides the Minimum - what is the maximum? Can it be 3072 or 4096?

I would say that "minimum" is sufficient - if there is some reason a CA wants to exceed it, that is up to the CA.  Certainly can be 3072 or 4096.  Especially since Microsoft seems to be pushing 4096, might want to set that as the RSA baseline for the root...

**Comment by lachellel** [comment]
Keep minimum of 2048
Allow for 3072 and 4096
