### ISSUE TITLE
6.1.13 Subscriber Key Pair Generation - Debian weak key

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#33]
Discuss debian weak key checks

> #### 6.1.1.3 Subscriber Key Pair Generation
> The CA SHALL reject a certificate request if the requested Public Key does not meet the requirements set forth in Sections 6.1.5 and 6.1.6 or if it has a known weak Private Key (such as a Debian weak key, see <http://wiki.debian.org/SSLkeys>).

**Comment by lachellel** [comment]
@grandamp

Wasn't this a FPKI TWG or CPWG topic?  A favorite of yours?

**Comment by LarryFrank** [comment]
As the one who does CPS analysis to decide if it is CP complaint, I am always nervous about open-ended statements like "or has a known weak Private Key."  What is required to verify that a CA is meeting that requirement - i.e., what does the CPS have to say/what does the CA have to do.  How do I (or anyone) know what the universe of known weak keys consists of?  (I do not recall a CPWG/TWG discussion, but maybe I missed it).

**Comment by grandamp** [comment]
Yep, a good topic, and I agree with Larry.  The CP could use better language, but the CPS should be precise.  I.e.,

-we track uniqness of each key signed
-all rsa moduli are analyzed via:
  - batch GCD for RNG failures
  - digested and checked for a match against example debian weak key moduli
  - ...

**Comment by grandamp** [comment]
@LarryFrank presentation attached

[gcd_and_coll_detection_20141218.pdf](https://github.com/uspki/policies/files/625406/gcd_and_coll_detection_20141218.pdf)

**Comment by LarryFrank** [comment]
A possible way to address this in CP language would be to reference a Fed PKI (or NIST) maintained document that specifies the set of checks that is required?  That way the CP doesn't need to be changed every time something new is discovered.  The PA would publicize when the document was updated so CAs would know they needed to update their procedures and have a specific timeline for conformance to the added check.

**Comment by lachellel** [comment]
Still open
@LarryFrank has good suggestions...but the document wanted for a reference doesn't exist? 
@grandamp any suggestions for policy language?

**Comment by LarryFrank** [comment]
> but the document wanted for a reference doesn't exist?
Agree - some entity (PA?) would have to be responsible for creating and maintain the document - capture the "current" set (whatever that is) and modify the document when a new weakness is found - with a date when CAs need to begin doing checks.
