### ISSUE TITLE
Section 2: Add CT to publishing info

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#336]
**Organization / Program:** DoD <br>**Section:** 2 <br>**PDF Page:** 24<br>**PDF Line(s):** N/A<br>**Comment:** There is a requirement later in the document to publish information to certificate transparency repositories, this requirement should be listed in section 2<br><br>**Suggested Change:** Add information about publication requirements for certificate transparency to section 2.

**Comment by lachellel** [comment]
Discussion needed.  

- Pre-certs are published to CT Logs as a requirement (to include SCTs in the x509 certificate extension)
- Certificates are not required to be published to CT Logs by the Subordinate CA

Should this type of information be included in Section 2, per the submitted comment.

**Comment by lachellel** [comment]
@tlsrus

I think this can be closed.  2nd set of eyes to review section 1 and 2 and see if it's adequate?

**Comment by TLSrUS** [comment]
o Agree with adding CT pre-certs to Sections 2.1 and 2.2.
o Should the CT logs be added to Section 1.3 ("Participants"), assuming that DoD will bring up a .gov/.mil CT log server??
o Section 3.2.6 says that any cross-certificates shall be disclosed publicly.  Should cross-certs be added to Sections 2.1 and 2.2?

**Comment by lachellel** [comment]
> o Agree with adding CT pre-certs to Sections 2.1 and 2.2.

Adding to 2.2 

> o Should the CT logs be added to Section 1.3 ("Participants"), assuming that DoD will bring up a .gov/.mil CT log server??

I don't think CT Logs need to be in Section 1.3 at this time.   It will confuse?

> o Section 3.2.6 says that any cross-certificates shall be disclosed publicly. Should cross-certs be added to Sections 2.1 and 2.2?

I think adding cross-certs to section 2.1 or 2.2 will be confusing.  We state that cross-certificates are not allowed without explicit permission.  The only reason a cross-certificate would ever be permitted is for subordinating to an existing trusted root CA - and at this time, this is not a path being pursued.
