### ISSUE TITLE
6.3.2 Certificate periods and key pair usage periods

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#35]
BRD: 
- https://github.com/uspki/policies/blob/master/certificate-policy.md#632-certificate-operational-periods-and-key-pair-usage-periods
- Only specifies Subscriber and "no greater than 39 months"

Common: 
- Specific to subscriber
- _For OCSP responders operating under this policy and all other subscriber public keys, the
maximum usage period is three years. Subscriber signature private keys have the same usage
period as their corresponding public key_

NIST 800-57: 
- http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57Pt3r1.pdf
- No specification found

It seems we have "39" versus "36" for subscriber keys; in this scenario, since enterprise _device_ certificates _may_ be issued under Common (non-Public Trust) and have a maximum of 36 months: 

- Suggest using the minimum of the two (36) as the maximum in the CP
- Promotes both alignment and ease for engineers trying to rectify the two (public trust versus enterprise)

**Comment by LarryFrank** [comment]
EV has a different requirement (27 months) - with a "recommendation" of 12 months.
Other than that - recommend we align with Common for max cert life - 20 years for root, 10 years for issuing CA, 3 years for subscriber.  Code signing may be different when we get to that...  FYI - DoD typically set "delegated" certs for OCSP responders to 45 days because of the "no-check" in the cert w/ automated renewal.

**Comment by lachellel** [comment]
36 months maximum (or below)
Add @LarryFrank comments

**Comment by lachellel** [comment]
from @techliaison and #45 

```
6.3.2
If a CA can only use the key to sign certs for 4 years and a subordinate CA cert can only be for 10 years then 20 years for the root seems excessive – shouldn’t need to be more than 15
And if subscriber certs can only be 3 years, the subordinate CA cert should not be greater than 7
I suggest changing the 4 year limit on signing certs –
· the Root should be able to sign for at least 9 years if it has a 20 year cert & can sign 10 year certs
· subordinates should be able to sign for 7 years if it has a 10 year cert and is signing 3 year cert
```


Questions: 

- Root max of 15 or 20? subordinate of 7 or 10?
- Multiple timeframes and options presented - which ones to draft include?

Constraints: 

- must be less than BRD requirements (shorter); 
- no constraints found in NIST SP 800-57; 
- NISTIR 7924 provides general guidance and top end lifetimes.

**Comment by LarryFrank** [comment]
I saw it was closed - current text has 4 year limit (I think) - but I am not seeing in BRD the requirement that limits the issuing CA to 4 years and it is silly to allow a CA to "live" for 10 years but only be allowed issue 3 year certs and require it to stop issuing at year 4...  BRD (Sept 2016 version) is silent on CA key usage.   If there is a CA/B Forum requirement, where is it stated?

**Comment by lachellel** [comment]
- CA/B Forum = only states subscriber lifetime explicitly

The 4 year text came from Common; discussions suggested aligning with Common; therefore draft suggestions aligned with Common. :-)

@techliaison is suggesting to removing the 4 year limit as well (not following Common); there is no requirement in CA/B or NIST for 4 year. 

It sounds like we have multiple suggestions to just drop the 4 year clause and leave the 20 / 10 (root / subordinate) max lifetimes.

Common:
```
The usage period for the Common Policy Root CA key pair is a maximum of 20 years.
For all other CAs operating under this policy, the usage period for a CA key pair is a maximum
of ten years. The CA private key may be used to sign certificates for at most four years, but may
be used to sign CRLs and OCSP responder certificates for the entire usage period. All
certificates signed by a specific CA key pair must expire before the end of that key pair’s usage
period.
```

**Comment by LarryFrank** [comment]
> It sounds like we have multiple suggestions to just drop the 4 year clause and leave the 20 / 10 (root / subordinate) max lifetimes.

I would recommend leaving out a limit on key usage.  CAs cannot issue a cert that lives beyond the CA lifetime.  While 3 years may be a MAX, it could issue less than 3 years in year 7+.  While DoD does routinely retire and replace CAs well before that - there have been instances where the new CA was not on line in time - potentially putting the PKI in violation of the CP...

Thanks.

**Comment by lachellel** [comment]
done... pr #45
