### ISSUE TITLE
Section 4.2.1: CAA and Issuer Domain Name

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#355]
**Organization / Program:** DoD <br>**Section:** 4.2.1 <br>**PDF Page:** 35<br>**PDF Line(s):** 738<br>**Comment:** Since there are couple of exception to CAA requirement, what is this field supposed to be?  The DNS name CA is under or values from CAA?  Also, if from CAA, should this include Issuer Domain Name for wild card certificates?<br><br>**Suggested Change:** Clarify

**Comment by lachellel** [comment]
@konklone and any others that want to comment!

Marking this issue for discussion.  The requirement seems clear to me, but an example and other changes may be needed.  The comment is for this sentence:

> The CA SHALL identify in Section 4.2 of the CPS the Issuer Domain Name(s) used for CAA records

Thoughts and proposed changes: 

- [ ] Issuer Domain Names is not in the Definitions.  Add "Issuer Domain Names" to Appendix A Definitions, and / or a reference to the RFC in Section 4.2.1. 
- [ ] Add an example to Section 4.2.1.

**Comment by konklone** [comment]
I'm not totally sure what's being asked -- maybe because I've never used CAA myself before. Each CA advertises what CAA hostnames they'll look for in customer CAA records, when evaluating whether they've been authorized/deauthorized to issue for a domain. Is there some ambiguity to that?

**Comment by lachellel** [comment]
I didn't think there was ambiguity.  The RFC(s) have examples.

**Comment by lachellel** [comment]
I'm making it the example so we can copy / paste.
