### ISSUE TITLE
6.2.1 Cryptographic module standards and controls

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#36]
See #34 

BRD: 
- https://github.com/uspki/policies/blob/master/certificate-policy.md#621-cryptographic-module-standards-and-controls
- No specification explicitly in this section; 
- inferred in 6.2.7 which specifies FIPS 140-2 Level 3 for CAs: https://github.com/uspki/policies/blob/master/certificate-policy.md#627-private-key-storage-on-cryptographic-module

Common: 
 - Allows both FIPS 140-2 Level 2 and Level 3 for the CAs and OCSP
- Subscribers "lowest" allowed is FIPS 140-2 Level 1
  - Inference is FIPS 140-2 is required at a minimum for any participant

NIST: 
- http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57Pt3r1.pdf
- Section 2.2.3
- _Ensure that Cryptographic modules for CAs, Key Recovery Servers, and OCSP
responders are hardware modules validated as meeting FIPS 140-2 Level 3 or higher_

**Comment by LarryFrank** [comment]
> •Subscribers "lowest" allowed is FIPS 140-2 Level 1 ◦Inference is FIPS 140-2 is required at a minimum for any participant

"lowest allowed" = "requirement"  Something may be inferred but like "practice notes" has no standing as a policy statement/requirement.  In general, web servers do not use level 2 or higher crypto modules as a PKI requirement - may do that for performance (e.g., optimized hardware for validation or other crypto processing)

**Comment by lachellel** [comment]
Reference FIPS 140-2 Level 1
Reference Common Criteria

**Comment by lachellel** [comment]
See #141 
Closing this issue in favor of the new issue (section 6 scrub)
