### ISSUE TITLE
fed.us Domain

### ISSUE THREAD

**Issue by buckaroogeek** [uspki/policies#38]
For better or worse, the US Forest Service has long used the fs.fed.us domain. We are actively (albeit slowly) moving the public facing web infrastructure to fs.usda.gov (forestservice.gov is not an option at this point) but we will likely have public web sites in the fs.fed.us domain for a while, and redirects from fs.fed.us to fs.usda.gov for substantially longer.

Could the fed.us domain be added to the *.mil and *.gov domains?

Brad

**Comment by ab** [comment]
See also https://github.com/uspki/policies/issues/12

**Comment by buckaroogeek** [comment]
thank you! Apologies for not seeing this earlier.
