### ISSUE TITLE
CAA records and mandating

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#39]
From @techliaison and Section 2 comments: 

- Do we want to mandate checking CAA records and honoring them? 
- Do we expect in the future that there would be CAA records for .gov and .mil limiting certificate issuance to this PKI?

**Comment by konklone** [comment]
> Do we expect in the future that there would be CAA records for .gov and .mil limiting certificate issuance to this PKI?

I do not expect that for `.gov` (and would not support that). This is especially true given that .gov includes non-federal organizations (and legislative and judicial branch orgs), but would be severely limiting in flexibility for even federal agencies. In addition, offices of inspector general may wish to use non-federal certificates for their `.gov` domains to maintain structural independence from their agency and reduce leverage or visibility that agency staff have over their operations.

I also think it's unlikely that `.mil` would be able to deploy such a policy, given the size and hetereogeneity of the `.mil` enterprise, and the oversight reasons mentioned above.

**Comment by konklone** [comment]
> Do we want to mandate checking CAA records and honoring them?

I would recommend we wait and see how the CABF proceeds on this issue, and lessons learned from broader deployment. This is also something we can add to our CP/CPS fairly rapidly later on, without needing to figure it out before applications.

**Comment by lachellel** [comment]
Updated: 

- CA/B Ballot for Review:                    Ballot 187 – Make CAA Checking Mandatory
  - _Start of Review Period:_           March 8, 2017 at 22:00 UTC
  - _End of Review Period:_             April 7, 2017 at 22:00 UTC


1.  #93 - would add / impact 3.2.2.x (3.2.2.8 per ballot) 
1. Check with DotGov and DotMil for CAA records in gov

**Comment by TLSrUS** [comment]
If the Fed root operated its DNS, would the exception policy in this proposal ("CAA checking is optional if the CA or an Affiliate of the CA is the DNS Operator of the domain's DNS.") permit us not to do CAA checking?

**Comment by lachellel** [comment]
Hmm...interesting read of it.  

What is the definition of the entity?  And "Affiliate of the CA"?  (It's not impacting the Root solely but the Issuing CAs) 

- **USG operates DotGov and DotMil**
- Breaking it down by agency - but we're all under the same policies -> DotMil operated by DoD, DotGov managed by GSA
- Therefore if we as USG manage the root and the Issuing CAs, and it's restricted to DotMil and DotGov...

This is the question:  Are **we** both the CA(s) and the DNS Operators in the spirit of CA/B?

**Comment by konklone** [comment]
> This is the question: Are we both the CA(s) and the DNS Operators in the spirit of CA/B?

The [BR definition of `Affiliate`](https://github.com/cabforum/documents/blob/master/docs/BR.md#161-definitions) is:

> A corporation, partnership, joint venture or other entity controlling, controlled by, or under common control with another entity, or an agency, department, political subdivision, or any entity operating under the direct control of a Government Entity.

So any federal agency would probably qualify as an "affiliate" of the GSA or DoD DNS operators, in my opinion.

In any case, I think the chances are basically nil that `.gov` could set any CAA records at all at the root level, given that over 4,000 of the ~5600 .gov domains are non-federal. And .mil is almost exclusively used by DoD, where the affiliate question is a lot less murky. 

So I *think* the point is moot...

**Comment by konklone** [comment]
> So I think the point is moot...

Re-reading, I think you're also talking about avoiding doing CAA checks on SLDs, not just the root. And I think as the definition reads right now, that yes you would be able to do that for known federal entities. (Which is a lot different than "any .gov domain", since most are non-federal.)

But if this is important to our operations, then we should probably ask CA/B for guidance and bring it up at the F2F.

**Comment by lachellel** [comment]
- Ballot 187: https://cabforum.org/2017/03/08/ballot-187-make-caa-checking-mandatory/
- Ballot 195: (minor wording edits)

Adding the 3.2.2.8 verbiage via branch Section3-updates

- https://github.com/uspki/policies/commit/cdbfb72e2691ca8cc069b34695f14e5f4b882386

Open questions on: 

> CAA checking is optional if the CA or an Affiliate of the CA is the DNS Operator (as defined in RFC 7719) of the domain’s DNS.


- Are we both the CA(s) and the DNS Operators in the spirit of CA/B? 
- What would this look like in practice for the non-federal govt entities (State, Local, Tribal, Territorial) under DotGov, which are out of scope for the intent and policy?
- For DotMil as solely US Federal Government - would CAA records need to be checked?

**Comment by lachellel** [comment]
need to modify the stock language for CAA records checks -> US gov policy and practice specific
closing this issue; we **are** including CAA records checks
