### ISSUE TITLE
Section 5.6: Key Changeover for a CA

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#397]
**Organization / Program:** DoD <br>**Section:** 5.6 <br>**PDF Page:** 55<br>**PDF Line(s):** 1375<br>**Comment:** CA signing keys are not changed "often" - the requirement is that they be changed every 10 years<br><br>**Suggested Change:** Define exceptional circumstances here in this section rather than using a vague reference. Describe under what circumstances would this action occur?

**Comment by lachellel** [comment]
Agree.  Additional considerations and proposed changes: 

- Section 5.6 was copied from versions of current US Federal PKI CPs where CAs operating under the same name perform rekeys
- Key changeovers are not applicable to this infrastructure and not allowed.  A new CA signing key constitutes a new CA; a different subject name (issuer ca 1, issuer ca 2, etc) must be used; notification of and approval of a new CA certificate being issued (from the root); inclusion in auditing; etc. 
- Proposing removal of the entirety of Section 5.6 

@LarryFrank @techliaison  - Any additional thoughts?

**Comment by LarryFrank** [comment]
> •Proposing removal of the entirety of Section 5.6

Recommend substituting "Key changeovers are not applicable to this infrastructure and shall not be done.  A new CA signing key constitutes a new CA with a different subject name." for the current text.

Just removing current text doesn't mean CA Changeover isn't permitted.  In a CP, what isn't specifically denied is "permitted".

**Comment by lachellel** [comment]
+1 - thanks!
