### ISSUE TITLE
reference NIAP profile for CA's?

### ISSUE THREAD

**Issue by cryptofilegsa** [uspki/policies#41]
The 2.0 protection profile from NIAP for operating CA's is here:
https://www.niap-ccevs.org/Profile/Info.cfm?id=404

Shall we adopt some of the guidance?  The Key Protection and Security Assurance requirements look particularly useful.

**Comment by lachellel** [comment]
they are useful...but which pieces where?

**Comment by cryptofilegsa** [comment]
from page ten: <img width="550" alt="pp-ca" src="https://cloud.githubusercontent.com/assets/22898229/21662151/de84f13e-d29d-11e6-85dc-8766b40b99fe.png">

**Comment by cryptofilegsa** [comment]
Also page 24 has a schema for a Searchable Certificate Repository including fields for:

-  subject name,
-  individual components of subject alternative name,
-  subject ID,
-  issuer ID,
-  algorithm ID,
-  public key,
-  key usage,
-  extended key usage,
-  serial number,

**Comment by lachellel** [comment]
will include references in arch writeup - don't need to be in policy...

agree?
