### ISSUE TITLE
Section 6.2.6 Private Key Transfer into or from a Cryptographic Module

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#44]
Per comments in #43 - all CAs shall be required to generate their own keys.  how should Section 6.2.6 be rewritten?

BRD: 

> If the Issuing CA generated the Private Key on behalf of the Subordinate CA, then the Issuing CA SHALL encrypt the Private Key for transport to the Subordinate CA. If the Issuing CA becomes aware that a Subordinate CA's Private Key has been communicated to an unauthorized person or an organization not affiliated with the Subordinate CA, then the Issuing CA SHALL revoke all certificates that include the Public Key corresponding to the communicated Private Key.

Common: 

> CA private keys may be exported from the cryptographic module only to perform CA key
> backup procedures as described in section 6.2.4.1. At no time shall the CA private key exist in
> plaintext outside the cryptographic module.
> All other keys shall be generated by and in a cryptographic module. In the event that a private
> key is to be transported from one cryptographic module to another, the private key must be
> encrypted during transport; private keys must never exist in plaintext form outside the
> cryptographic module boundary.
> Private or symmetric keys used to encrypt other private keys for transport must be protected
> from disclosure

**Comment by LarryFrank** [comment]
1.  I would state (in 6.1.1) that CAs always generate their own keys in the CAs FIPS 140-2 Level 3 module.


Second - 6.2.6 - use the Common language - which does allow for "export" "CA private keys may be exported from the cryptographic module only to perform CA key backup procedures." and then state (from BR) " If the Issuing CA becomes aware that a Subordinate CA's Private Key has been communicated to an unauthorized person or an organization not affiliated with the Subordinate CA, then the Issuing CA SHALL revoke all certificates that include the Public Key corresponding to the communicated Private Key."

So, drop the first sentence from BRD above.  Also, could/should keep the rest of the Common text related to non CA keys.
