### ISSUE TITLE
Certificate Profiles: Section 7.1.4.2.2 Subject Distinguished Name Fields

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#46]
We have different edits (from docs!) for the Subject Distinguished Name Fields: 

- https://github.com/uspki/policies/blob/master/certificate-policy.md#71422-subject-distinguished-name-fields

Opening issue to _collect_ and _discuss_ the various edits.

**Comment by lachellel** [comment]
Proposed edits from @larryfrank: 

a. Certificate Field: subject:commonName (OID 2.5.4.3) 
Required ~~/Optional~~:  ~~Deprecated (Discouraged, but not prohibited)~~ 
Contents: If present, this field MUST contain a single IP address or Fully-Qualified Domain Name that is one of the values contained in the Certificate's subjectAltName extension (see Section 7.1.4.2.1).

b. Certificate Field: subject:organizationName (OID 2.5.4.10) 
~~Optional.~~ Required
Contents: This field SHALL contain O=U.S. GOVERNMENT.
~~If present, the subject:organizationName field MUST contain either the Subject's name or DBA as verified under Section 3.2.2.2. The CA may include information in this field that differs slightly from the verified name, such as common variations or abbreviations, provided that the CA documents the difference and any abbreviations used are locally accepted abbreviations; e.g., if the official record shows "Company Name Incorporated", the CA MAY use "Company Name Inc." or "Company Name". Because Subject name attributes for individuals (e.g. givenName (2.5.4.42) and surname (2.5.4.4)) are not broadly supported by application software, the CA MAY use the subject:organizationName field to convey a natural person Subject's name or DBA.~~

~~c. Certificate Field: subject:givenName (2.5.4.42) and subject:surname (2.5.4.4) 
Optional. Contents: If present, the subject:givenName field and subject:surname field MUST contain an natural person Subject’s name as verified under Section 3.2.3. A Certificate containing a subject:givenName field or subject:surname field MUST contain the (2.23.140.1.2.3) Certificate Policy OID.~~

~~d. Certificate Field: Number and street: subject:streetAddress (OID: 2.5.4.9) Optional if the subject:organizationName field, subject: givenName field, or subject:surname field are present. Prohibited if the subject:organizationName field, subject:givenName, and subject:surname field are absent. Contents: If present, the subject:streetAddress field MUST contain the Subject's street address information as verified under Section 3.2.2.1.~~

~~e. Certificate Field: subject:localityName (OID: 2.5.4.7) Required if the subject:organizationName field, subject:givenName field, or subject:surname field are present and the subject:stateOrProvinceName field is absent. Optional if the subject:stateOrProvinceName field and the subject:organizationName field, subject:givenName field, or subject:surname field are present. Prohibited if the subject:organizationName field, subject:givenName, and subject:surname field are absent. Contents: If present, the subject:localityName field MUST contain the Subject's locality information as verified under Section 3.2.2.1. If the subject:countryName field specifies the ISO 3166-1 user-assigned code of XX in accordance with Section 7.1.4.2.2(g), the localityName field MAY contain the Subject's locality and/or state or province information as verified under Section 3.2.2.1.~~

~~f. Certificate Field: subject:stateOrProvinceName (OID: 2.5.4.8) Required if the subject:organizationName field, subject:givenName field, or subject:surname field are present and subject:localityName field is absent. Optional if the subject:localityName field and the subject:organizationName field, the subject:givenName field, or the subject:surname field are present. Prohibited if the subject:organizationName field, the subject:givenName field, or subject:surname field are absent. Contents: If present, the subject:stateOrProvinceName field MUST contain the Subject's state or province information as verified under Section 3.2.2.1. If the subject:countryName field specifies the ISO 3166-1 user-assigned code of XX in accordance with Section 7.1.4.2.2(g), the subject:stateOrProvinceName field MAY contain the full name of the Subject's country information as verified under Section 3.2.2.1.~~

~~g. Certificate Field: subject:postalCode (OID: 2.5.4.17) Optional if the subject:organizationName, subject:givenName field, or subject:surname fields are present. Prohibited if the subject:organizationName field, subject:givenName field, or subject:surname field are absent. Contents: If present, the subject:postalCode field MUST contain the Subject's zip or postal information as verified under Section 3.2.2.1.~~

h. Certificate Field: subject:countryName (OID: 2.5.4.6) 
Required ~~if the subject:organizationName field, subject:givenName, or subject:surname field are present. Optional if the subject:organizationName field, subject:givenName field, and subject:surname field are absent.~~
Contents: This field SHALL contain C=US.
~~If the subject:organizationName field is present, the subject:countryName MUST contain the two-letter ISO 3166-1 country code associated with the location of the Subject verified under Section 3.2.2.1. If the subject:organizationName field is absent, the subject:countryName field MAY contain the two-letter ISO 3166-1 country code associated with the Subject as verified in accordance with Section 3.2.2.3. If a Country is not represented by an official ISO 3166-1 country code, the CA MAY specify the ISO 3166-1 user-assigned code of XX indicating that an official ISO 3166-1 alpha-2 code has not been assigned.~~

i. Certificate Field: subject:organizationalUnitName 
Optional. 
Contents: This field SHALL contain OU=<U.S. GOVERNMENT Agency> which controls the server to which the certificate is issued.  The value is verified in accordance with Section 3.2.2.1.
~~The CA SHALL implement a process that prevents an OU attribute from including a name, DBA, tradename, trademark, address, location, or other text that refers to a specific natural person or Legal Entity unless the CA has verified this information in accordance with Section 3.2 and the Certificate also contains subject:organizationName, subject:givenName, subject:surname, subject:localityName, and subject:countryName attributes, also verified in accordance with Section 3.2.2.1.~~

j. Other Subject Attributes All other optional attributes, when present within the subject field, MUST contain information that has been verified by the CA. Optional attributes MUST NOT contain metadata such as '.', '-', and ' ' (i.e. space) characters, and/or any other indication that the value is absent, incomplete, or not applicable.

**Comment by lachellel** [comment]
moved from pull request #69
from @techliaison

If this CP is going to be restricted to issuing for US Government certificates we should be much more restrictive in the subject names forms - I suggest the following for 7.1.4.2.2:

7.1.4.2.2:
a. Certificate Field: subject:commonName (OID 2.5.4.3) Required/Optional: Deprecated (Discouraged, but not prohibited) Contents: If present, this field MUST contain a single Fully-Qualified Domain Name that is one of the values contained in the Certificate's subjectAltName extension (see Section 7.1.4.2.1).
b. Certificate Field: subject:organizationName (OID 2.5.4.10) Required. Contents: The subject:organizationName field SHALL contain U.S. Government.
e. Certificate Field: subject:localityName (OID: 2.5.4.7) Optional Contents: If present, the subject:localityName field SHALL contain the Subject's locality information as verified under Section 3.2.2.1.
f. Certificate Field: subject:stateOrProvinceName (OID: 2.5.4.8) Optional Contents: If present, the subject:stateOrProvinceName field SHALL contain the Subject's state information as verified under Section 3.2.2.1.
g. Certificate Field: subject:postalCode (OID: 2.5.4.17) Optional Contents: If present, the subject:postalCode field MUST contain the Subject's zip or postal information as verified under Section 3.2.2.1.
h. Certificate Field: subject:countryName (OID: 2.5.4.6) Required. Contents: the subject:countryName SHALL contain the two-letter ISO 3166-1 country code US.
i. Certificate Field: subject:organizationalUnitName Optional. The CA SHALL implement a process to verify this information in accordance with Section 3.2
j. Other Subject Attributes All other optional attributes, when present within the subject field, SHALL contain information that has been verified by the CA. Optional attributes SHALL NOT contain metadata such as '.', '-', and ' ' (i.e. space) characters, and/or any other indication that the value is absent, incomplete, or not applicable.

**Comment by LarryFrank** [comment]
DoD CPS cert profile likely will make subject CN required and specify the DN in such a way that all the "optional" location data is not allowed as it does today for the subject DN.  I prefer to eliminate text that is "dead" (like unused code - not actually useful if never executed).  May confuse people (which is harmful if no one is actually using it).  If someone decides to challenge DoD's practice because of the text - that could be very harmful.

**Comment by lachellel** [comment]
See #74 

after merge, there are new drafts for each certificate profile and the CRL profile

**Comment by lachellel** [comment]
Well - it seems some of these edits and the profiles are not aligned with the details of the BRD.   :1st_place_medal:  for us!! 

It's the **optional** use of "organizationName" that introduces the logic complexities.  

Take a look at the clean BR and then the logic chain with the profiles and edits:

- Clean BR: https://github.com/cabforum/documents/blob/9f3404f3fa0f373867e25b9c63f642961b1f6bb9/docs/BR.md

Logic chain when applying edits one by one: 

- organizationName: Optional, if present must be O=U.S. Government
-  IF organizationName is present: 
  - EITHER localityName OR stateOrProvinceName is REQUIRED

To look at the logic, you can review this commit in a fork where i started stripping out the extraneous: 

- https://github.com/lachellel/policies-uspki-lrl/commit/2296f47d400bcbf2947da89a2a0f7d308e84d226

I also think there is an nit with the BR in Section 7.1.4.2.2(f) - which references Section 7.1.4.2.2(g) BUT intends to reference 7.1.4.2.2(h) for country code?

**Comment by lachellel** [comment]
Above is only when organizationName is Optional and present.  When I started weaving in the Required for organizationName is where the mismatches became more apparent!

**Comment by lachellel** [comment]
For the optional items that introduce complexity but do not have good USG applicability, specify as Prohibited: 

- https://github.com/uspki/policies/blob/master/certificate-policy.md#71422-subject-distinguished-name-fields
- Postal Code
- Street Address

**Comment by LarryFrank** [comment]
>  •EITHER localityName OR stateOrProvinceName is REQUIRED

This is not clear to me - under locality it also says (under contents) "If the subject:countryName field specifies the ISO 3166‐1 user‐assigned code of XX in accordance with Section 7.1.4.2.2(g), the
localityName field MAY contain the Subject’s locality and/or state or province information as
verified under Section 3.2.2.1."  which seems to modify the "required clause"

stateOrProvinceName has essentially the same text.

We can put "Washington DC" in all of them - but is not informative in any way - just added text in the name - contributing to certificate bloat.

**Comment by lachellel** [comment]
@LarryFrank 

Let's finalize the discussion on this one?

- If we're requiring Organization Name
- We have to have either localityName or stateOrProvinceName
- Washington, DC was an option discussed


Also - I did a bad replace that impacted (e) and (f)!   Need to update to remove "US".

**Comment by LarryFrank** [comment]
I think it is appropriate we says "OU=US Government."  Since the policy seems to want it, we should also say location is  Washington DC.  Makes it clear this IS a US Government operated entity and doesn't make things any harder at issuance...

**Comment by lachellel** [comment]
Notes from the discussion: 

- Link the certificate profiles and subject information to Section 3.2.2.x for
  - Country
  - Organization

Update Sections 3.2.2.x accordingly

**Comment by lachellel** [comment]
Any impact for Ballot 191:

- https://cabforum.org/2017/05/23/ballot-191-clarify-place-business-information/

**Comment by LarryFrank** [comment]
> Ballot 191

So, the Ballot appears to only address requirements for location data in EV certs.  Good reason to just say "No EV".

**Comment by lachellel** [comment]
fixed by this commit (rolled into the section 3 PR https://github.com/uspki/policies/pull/150/commits/f42b19a4530e3d8aac90b25a358e0e196799e57e)
