### ISSUE TITLE
Section 3.2.2.4.10 TLS Using a Random Number

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#463]
**Organization / Program:** DoD 
**Section:** 3.2.2.4.10 
**PDF Page:** 30
**PDF Line(s):** 603-605
**Comment:** It is not clear how a random value in certificate can be used to authenticate since certificate can be public.  Describe this method in more detail.  May be this is related to Section 7.2 of the ACME protocol

**Suggested Change:** First time the acronym is used

**Comment by lachellel** [comment]
Reference one of the process flows: 

- https://github.com/uspki/policies/blob/master/flows/domain-auth-methods.md

A secondary process flow reviewed was: 

- CA generates Random Value  
- Applicant generates key pair and self-signed cert with Random Value (e.g. using openssl and placing random value as CN)
- Cert is served up at the requested FQDN over TLS on an Authorized Port
- CA connects to the FQDN and verifies the Random Value

**Comment by lachellel** [comment]
@konklone @techliaison

Thoughts on whether to describe this validation method in more detail in the CP?   It seems clear to me -
 however, I've also been involved in the conversations. 

This method is similar to "Agreed-Upon Change to Website".  Rather than the Random Value or Request Token being at a URI (e.g. /.well-known/pki-validation), the Random Value is in a Certificate that is served via a TLS handshake.  The Certificate can be self generated / self-signed, and confirms the Applicant has control over the requested FQDNs.

**Comment by lachellel** [comment]
> May be this is related to Section 7.2 of the ACME protocol

Example is **Section 8.4** of the ACME Protocol: _TLS with Server Name Indication (TLS SNI) Challenge_

**Comment by konklone** [comment]
Yes, I think this doesn't need any elaboration here. It's exactly like the Agreed-Upon Change to Website -- you're not exchanging a secret, but rather you're showing that you can put an unpredictable value into a predictable place that only someone with technical control over the domain can do.

**Comment by LarryFrank** [comment]
> how a random value in certificate can be used 

CP doesn't say "how".   It says what is required - a CPS says how the requirment is impelmented.  The less "how" in the CP the better as far as I am concerned.  So agree it doesn't need elaboration.

**Comment by lachellel** [comment]
I did add **an example**, and am adding references for ACME.

**Comment by lachellel** [comment]
closed by PR #498
