### ISSUE TITLE
Section 4.1

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#47]
Recommend some information on the criteria and contents for submitting a certificate application be included here.  FPKI COMMON Policy provides good candidate language.
"The Certificate application process must provide sufficient information to:
 Establish the applicant’s authorization to obtain a certificate. 
 Establish and record identity of the applicant. 
 Obtain the applicant’s public key and verify the applicant’s possession of the private key for each certificate required."

**Comment by LarryFrank** [comment]
Removed "•	Verify any role or authorization information requested for inclusion in the certificate. "
