### ISSUE TITLE
CA terminology: Fix

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#481]
Choose and fix throughout the CP the use of: 

- The CA
- All CAs
- Issuing CAs (which is all CAs - but used in the possessive in some areas; "the Issuing CA" is the issuer of the certificate and requirement impacting that certificate)

**Comment by LarryFrank** [comment]
Not sure I agree it is a bug.

Issuing CAs vs all CAs.  Issuing CAs are those which issue to subscribers and all CAs includes the Root (which does not issue to subscribers - issues to other CAs).

Where "CA" is used in the singlular, is is applicable to every CA in the PKI (e.g., all).  Whether it is "all" or "a" or "the" - is more gramar than substantive.  Probably need to look at each use of CA and ensure the symantic are not in error.
