### ISSUE TITLE
Section 4.9.7 CRL Issuance Frequency (combining four comments into one thread)

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#482]
Combining four overlapping or duplicative comments into one thread.

| Organization / Program | PDF Line | Section | Comment | Change | Original Issue |
| --- | --- | --- | --- | --- | --- |
| DoD | 972-974 | 4.9.7 | Issuing CRLs   every 31 days with a validity period of no more than 32 days doesn't provide   much of a window for something to go wrong with publishing the certificate. | ~~striking original change; mismatch of comment and suggested change~~ | https://github.com/uspki/policies/issues/365 |
| DoD |  972-974 | 4.9.7 | One   day grace period is not enough | Either   change 31 or 32.  Prefer changing 32 to   35 or more | https://github.com/uspki/policies/issues/366 |
| NSA |  972-974 | 4.9.7 | If   the CRL is to issued every 31 days, the nextUpdate field should give more   overlap to allow for distribution of the CRL. | check   what DOD does - issued every 30 days, 45 day      nextUpdate | https://github.com/uspki/policies/issues/367 |
| DoD |   | 4.9.7 | The   Root CRL publication requirement is significantly stricter than that required   by the CA/B forum BR. | Change   the Root requirement to match the CA/B BR "The CA SHALL update and   reissue CRLs at least (i) once every twelve months and (ii) within 24 hours   after revoking a Subordinate CA Certificate, and the value of the nextUpdate   field MUST NOT be more than twelve months beyond the value of the thisUpdate   field." | https://github.com/uspki/policies/issues/368 |

**Comment by LarryFrank** [comment]
IF GSA is going to operate the root - then this is there problem to decide what they need/what they will do in operation.  If DoD (aka NSA) will operate, it should be changed to reflect what they do in practice now.  All is well withint the CA/B forum requirements.

**Comment by lachellel** [comment]
Don't agree with the comment. :-)  It's the USG's decision as a whole and our wonderful delegation of authority, not any individual unit or program.  

The original statements in the CP was supposed to be what we (across govt) "do in practice now" to maintain synergy.    We got it wrong obviously.  

I can't think of a good reason _outside_ of our current FPKI and cross-cert / issuance happy infrastructure why the Root CA would need to issue more than every 12 months.

**Comment by techliaison** [comment]
Even though some browsers may decide to ignore revocation in favor of their own non standard methods of distrusting a subordinate CA - in the off chance that a CA is compromised or decides to terminate early it would be nice to be able to revoke the associated CA certificate.  If you have previously published a 12 month CRL, for any RP that actually supports revocation checking via the CRL, you have basically limited the ability to revoke that certificate for up to the 12 months, if the reason to revoke happens shortly after the 12 month CRL was issued.  12 months may seem a bit excessive when viewed in that light. And having that infrequent an update to CRLs may have contributed to some browsers deciding they couldn't rely on CRLs and had to develop their own method of distrusting an intermediate CA quicker.

**Comment by LarryFrank** [comment]
What we do in practice can be much more limited than what the policy says. Know all about the arguments on longer vs shorter CRL life.  The original comment recommendation was to adopt the policy the CA/B Forum REQUIRES.   The problem - NSA uses 35 days (for whatever reason - don't ask me why...  The policy language currently is very specific and very limited and would require a change to the way the NSA Root room operates.  If GSA is opertaing the Root and they are OK with the current language, then reject the comment.  If it is still up in the air - need to loosen it SOME if not reverting to the CA/B BR.   I agree 12 months is unreasonably long...  35 days vs 32 isn't a big deal.

**Comment by lachellel** [comment]
Agree that the minor discrepancies in days might not matter!  I'm currently looking for consistency (to reduce inconsistent requirements for O&M).   

A few additional comments solely for clarity: 

> Even though some browsers may decide to ignore revocation in favor of their own non standard methods of distrusting a subordinate CA - in the off chance that a CA is compromised or decides to terminate early it would be nice to be able to revoke the associated CA certificate. 
> If you have previously published a 12 month CRL, for any RP that actually supports revocation checking via the CRL, you have basically limited the ability to revoke that certificate for up to the 12 months, if the reason to revoke happens shortly after the 12 month CRL was issued. 

Taking these two sentences together, we have to look at the other compensating controls.  
- In either of these scenarios (compromise or termination), the End Entity certificates are required to be revoked even before the CA Certificate is revoked.  
- If the user-agent actually supports revocation checking via the CRL, the End Entity certificates will show as revoked first.  
- A new CRL from Root CA does get published.  The core problem would actually be caching behavior (based on Next Update) in operating systems and proxies (etc). 

See diagram in:  https://github.com/uspki/policies/issues/58

**Comment by lachellel** [comment]
Discussion outcome: 

- Maintain alignment with Common CP and practices
- 31 and 32 days respectively
- Verify against all trust store operator requirements

**Comment by lachellel** [comment]
closed by PR #498
