### ISSUE TITLE
Section 1.5.4: Remove compliance analysis prior to submitting the CPS

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#483]
- 12/7/2018 discussions
- DoD, GSA recommended change

**Current text:** 

> Prior to submitting a CPS, the CA shall commission a compliance analysis study culminating in a written report that provides a summary of areas in which the CPS may not or does not comply with this CP. The compliance analysis shall be performed by an independent party.

**Suggested Change:**  Remove entirely.   
**Reason:** Too many compliance steps.

**Comment by LarryFrank** [comment]
Compliance analysis has to be done before the CPS is "approved" - whether it is done by the CA or the PA, it needs to be done.  In the Fed PKI, they rely on the compliance auditor.  DoD does it separately (does not drag the compliance auditor into the mix until it is time to do an audit).  

Common CP says "The FPKIPA shall make the determination that a CPS complies with this policy. The CA and RA must meet all requirements of an approved CPS before commencing operations."  In practice, it seems that practice statement complaince is left to the compliance auditor to determine - which often is AFTER a practice has been approved and implemented...

An analysis of the document needs to happen BEFORE it is approved.
