### ISSUE TITLE
Section 4.1.2 Enrollment process and responsibilities

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#49]
The term "certificate request" is not defined in Section 1.6.  Is this the pkcs#10 request?  If so, it will be signed by the device (web server) that is the subject of the certificate request, not by the "appropriate Applicant Representative on behalf of the Applicant". 
Is the paragraph that starts: "One certificate request MAY suffice. . ." correct?  or should it say ". . .provided that each Certificate is supported by a valid, current _subscriber agreement_. . ."

**Comment by LarryFrank** [comment]
The fuzzy words "certificate request" generally INCLUDES a PKCS#10 but also has other stuff besides that.  I am in favor of not making at any more specific then the BR text.
