### ISSUE TITLE
Chromium.org link

### ISSUE THREAD

**Issue by michaelblyons** [uspki/policies#496]
I keep getting a "Connection Reset" for the [Google Chromium link][blame-1] on the Background page. ([Also on][blame-2] the RFC page.)

Should it link here instead? [`https://www.chromium.org/Home/chromium-security/certificate-transparency`][cert-trans]

[blame-1]: https://github.com/uspki/policies/blame/master/pages/00-background.md#L32
[blame-2]: https://github.com/uspki/policies/blame/master/pages/01-request-for-comment.md#L36
[cert-trans]: https://www.chromium.org/Home/chromium-security/certificate-transparency

**Comment by konklone** [comment]
They're identical pages, so yeah, I expect that the chromium.org URL is more stable and implementation-agnostic than the underlying sites.google.com URL. If you'd like to file a PR, I'd be happy to review and merge it.

You may want to look into why your network is blocking sites.google.com, though - that's a popular hostname and service.
