### ISSUE TITLE
CAB Forum Ballot 218:  Domain Authorization Docs and deprecation / updates

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#502]
Adding this issue to track CAB Forum Ballot 218:  https://cabforum.org/pipermail/public/2018-January/012673.html

The ballot is being debated and would deprecate two domain validation methods: 

- 3.2.2.4.1
- 3.2.2.4.5

One (3.2.2.4.5) of the two methods is currently included in our policy.

**Comment by lachellel** [comment]
- We are not using Domain Authorization Documents in design and practice
- Can be removed from the CP draft

**Comment by konklone** [comment]
Closed by #518.
