### ISSUE TITLE
Update certificate profiles for Name Constraints

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#507]
Additional comments from development:

- add the DirNames to permitted (see https://github.com/uspki/policies/issues/440)
- Specific to **CNG** libraries processing for IE / Edge...+ check chrome on windows os devices
- Testing different configurations

**Comment by lachellel** [comment]
**Notes and findings on Name Constraints:** 

Referencing certificate profiles and section 7.1.5 of **this** CP: 
- [Subordinate CA cert profile](https://github.com/uspki/policies/blob/master/certificate-profile-subordinate-CA.md)
- [Section 7.1.5](https://github.com/uspki/policies/blob/master/certificate-policy.md#715-name-constraints)


**Notes and Actions:** 
- Add DirNames to Permitted
- Add TWO entries for Permitted DirNames (forward and reverse)
  - S=District of Columbia,O=U.S.Government,c=US
  - c=US, o=U.S. Government, S=District of Columbia
  - (apply proper formatting)
- Reason for adding both = uneven processing across all possible libraries
- Outstanding item is for the CA that will issue both DV and OV
  - For the profiles in this CP, DV may include c=US but may also only have CN
  - c=US would be covered by the permitted values
  - empty would not

**Other issues:** 
There is a potential gap or confusing requirement in the Baseline Requirements:
- In Section 7.1.5, DNSName + DirNames + IPAddress are explicitly identified as values required for Name Constraints (and inclusion in either permitted or excluded or both)
- The scenarios for no IP address and no DNSName are covered
- The scenarios for DV certificates which do **not** require **any** subject information is not covered  
- For DV certificates, a zero length DirNames would need to be included in permitted
- For a CA that issues **both** DV and OV end entity certificates, a zero length DirNames may also need to be included in permitted

**Additional references:** 
- [Netflix developed Name Constraints Test Tools and Findings](https://nameconstraints.bettertls.com/)

Thanks to @fotisl for insight into HARICA's implementation of Name Constraints and lessons learned. 
 Thanks to @rmhrisk for insight into lessons learned. 

All comments and clarifications welcome.

**Comment by rmhrisk** [comment]
My pleasure.

**Comment by fotisl** [comment]
Always glad to help.

Just to clarify, an empty DirName constraint is a 'wildcard', since it matches everything. Thus, there is no need to include both an empty DirName and the DirNames that will match O,S,C, unless C is included in all end-entity DV certificates and you don't include the empty DirName but just C=US. If you go with the empty DirName, since there will be at least one DV certificate, the empty DirName constraint should be included in all SubCAs.

I would be glad to generate a sample CA structure to verify this.

**Comment by lachellel** [comment]
@fotisl No need!  We're generating these already and testing.  Thanks so much. 

Actions: 

- Add DirNames to Permitted
- Add ONE entry for Permitted DirNames 
- c=US

@ryancdickson

**Comment by ryancdickson** [comment]
Sample certificate to include updated nameConstraints pasted below.

```
-----BEGIN CERTIFICATE-----
MIIGIjCCBAqgAwIBAgIVAMweIKAPD3AEgKrMBasB/hARAaszMA0GCSqGSIb3DQEB
CwUAMFExCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVybm1lbnQxKDAm
BgNVBAMTH1VTIEZlZGVyYWwgVGVzdCBUTFMgUm9vdCBDQSAxMDAwHhcNMTgwNDA0
MTcwMTQyWhcNMjgwNDAxMTcwMTQyWjBMMQswCQYDVQQGEwJVUzEYMBYGA1UEChMP
VS5TLiBHb3Zlcm5tZW50MSMwIQYDVQQDExpVUyBGZWRlcmFsIFRlc3QgVExTIENB
IDEwMDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKSDjOSMuq1IyuWD
8uCQ7ocFFxJCDk5oKUQkkwZnGKmphQDWgvgewhmeT5kmAAh0yXhtlCe+gOts78Bk
LdL/bhsbp3pEh9xUnMX2PPY97nJwWyydmyyg4TiatWG3yv9iKP4fPA2F7Ea42qLu
RCq2WtFPAz0/nFa3jHszYkb0QM6Xu15BSONczzfAMxYWRcoDmEul2DhDs40m0R8B
D7cpIQIXRC0vKVHK0tCS7bnyc1OqWF8InTcWQzMewklJuDSjVtVG8oyRyTLtyToH
oMjWbcm9AKPjQwHewHjEENeskidxvleQF6C1gE9T1Q64bFGHnZaksZzVD2ddIZNV
+e7tResCAwEAAaOCAfQwggHwMB0GA1UdDgQWBBSTyEo3mc0Pt5lClW/HpKI9PsMv
3jAfBgNVHSMEGDAWgBS/QyDGCmdD9bbSWhCg7xzvn3a7VzASBgNVHRMBAf8ECDAG
AQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwOQYDVR0gBDIwMDAMBgpghkgBZQMCAQMrMAwGCmCGSAFlAwIBAywwCAYG
Z4EMAQIBMAgGBmeBDAECAjCBhAYIKwYBBQUHAQEEeDB2MCsGCCsGAQUFBzABhh9o
dHRwOi8vb2NzcC50bHNyb290LnBraS1sYWIuZ292MEcGCCsGAQUFBzAChjtodHRw
Oi8vY2VydC50bHNyb290LnBraS1sYWIuZ292L3NpZ24vVVNGRURURVNUUk9PVENB
MTAwLnA3YzBGBgNVHR8EPzA9MDugOaA3hjVodHRwOi8vdGxzcm9vdC5wa2ktbGFi
Lmdvdi9jcmwvVVNGRURURVNUUk9PVENBMTAwLmNybDBhBgNVHR4BAf8EVzBVoCEw
EaQPMA0xCzAJBgNVBAYTAlVTMAWCA21pbDAFggNnb3ahMDAKhwgAAAAAAAAAADAi
hyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADANBgkqhkiG9w0BAQsF
AAOCAgEAVXF1F6XpmXXJoCaDN4xeuEki0l3Z41Q4tMUNaITqnkVbp6TN6i9bmJOK
RlgSrVmpyHVp/Dsm90OnEg+29yblEZ0iKt8WfhHOTE4iM3kDC4QTnEA2PcyfqQT+
1dNogq3pvL4bd8q2m/WXmBGNcFqEy4iMzgbtQhL3JD6Crly8sz2Vb90IKycViT9h
hgw15NCcvEb8UZUcO5PAvE9E02U50Ox5WEkWSmdhfCn4VL8PWfMY14cNLEBsbuO/
GP2eghmJADMFPtQjGpsq47Un61aY4aMRxEDBgYIOWQ4JdzBE/3BSAjnHgtCV+uA2
u5zuBypSuUnclbcETKj5bd92zHg3oZFrFzCWm3z3FWpfJOlZfXaIt7eZs7PMm477
jIFcFidcHtfX2umo9QXeZKd0AHDz5TUNX8j9C9GlqXTEwKM1EVFCPaeF4IHREggU
UaxEk6PDQQo8oYulNyCrvsnHybMW/ltp4oFco/vgdFQhq7+DVro1Xm28OcRlmnBq
neN0yZLUrHwdS3S4/PcEr1kIK7m0zJ8NWf4WZGWeinnn5sgNu4Dex4RAPQTx9qeA
AzfDihGvfIELcyFYCvH/Yx2G/PqTJJ2wBW61fwykKlEXYOQehDYKRh1UukZwHKKl
cMxvtXZcsjbUMpojHSmin84QLoMBdb4nN/TDsYb8LwQ9bvfXVVY=
-----END CERTIFICATE-----
```
```
>openssl x509 -noout -text -in SUB\certs\subordinate.cert.cer
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            cc:1e:20:a0:0f:0f:70:04:80:aa:cc:05:ab:01:fe:10:11:01:ab:33
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=U.S. Government, CN=US Federal Test TLS Root CA 100
        Validity
            Not Before: Apr  4 17:01:42 2018 GMT
            Not After : Apr  1 17:01:42 2028 GMT
        Subject: C=US, O=U.S. Government, CN=US Federal Test TLS CA 100
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a4:83:8c:e4:8c:ba:ad:48:ca:e5:83:f2:e0:90:
                    ee:87:05:17:12:42:0e:4e:68:29:44:24:93:06:67:
                    18:a9:a9:85:00:d6:82:f8:1e:c2:19:9e:4f:99:26:
                    00:08:74:c9:78:6d:94:27:be:80:eb:6c:ef:c0:64:
                    2d:d2:ff:6e:1b:1b:a7:7a:44:87:dc:54:9c:c5:f6:
                    3c:f6:3d:ee:72:70:5b:2c:9d:9b:2c:a0:e1:38:9a:
                    b5:61:b7:ca:ff:62:28:fe:1f:3c:0d:85:ec:46:b8:
                    da:a2:ee:44:2a:b6:5a:d1:4f:03:3d:3f:9c:56:b7:
                    8c:7b:33:62:46:f4:40:ce:97:bb:5e:41:48:e3:5c:
                    cf:37:c0:33:16:16:45:ca:03:98:4b:a5:d8:38:43:
                    b3:8d:26:d1:1f:01:0f:b7:29:21:02:17:44:2d:2f:
                    29:51:ca:d2:d0:92:ed:b9:f2:73:53:aa:58:5f:08:
                    9d:37:16:43:33:1e:c2:49:49:b8:34:a3:56:d5:46:
                    f2:8c:91:c9:32:ed:c9:3a:07:a0:c8:d6:6d:c9:bd:
                    00:a3:e3:43:01:de:c0:78:c4:10:d7:ac:92:27:71:
                    be:57:90:17:a0:b5:80:4f:53:d5:0e:b8:6c:51:87:
                    9d:96:a4:b1:9c:d5:0f:67:5d:21:93:55:f9:ee:ed:
                    45:eb
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                93:C8:4A:37:99:CD:0F:B7:99:42:95:6F:C7:A4:A2:3D:3E:C3:2F:DE
            X509v3 Authority Key Identifier:
                keyid:BF:43:20:C6:0A:67:43:F5:B6:D2:5A:10:A0:EF:1C:EF:9F:76:BB:57

            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Certificate Policies:
                Policy: 2.16.840.1.101.3.2.1.3.43
                Policy: 2.16.840.1.101.3.2.1.3.44
                Policy: 2.23.140.1.2.1
                Policy: 2.23.140.1.2.2

            Authority Information Access:
                OCSP - URI:http://ocsp.tlsroot.pki-lab.gov
                CA Issuers - URI:http://cert.tlsroot.pki-lab.gov/sign/USFEDTESTROOTCA100.p7c

            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://tlsroot.pki-lab.gov/crl/USFEDTESTROOTCA100.crl

            X509v3 Name Constraints: critical
                Permitted:
                  DirName: C = US
                  DNS:mil
                  DNS:gov
                Excluded:
                  IP:0.0.0.0/0.0.0.0
                  IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0

    Signature Algorithm: sha256WithRSAEncryption
         55:71:75:17:a5:e9:99:75:c9:a0:26:83:37:8c:5e:b8:49:22:
         d2:5d:d9:e3:54:38:b4:c5:0d:68:84:ea:9e:45:5b:a7:a4:cd:
         ea:2f:5b:98:93:8a:46:58:12:ad:59:a9:c8:75:69:fc:3b:26:
         f7:43:a7:12:0f:b6:f7:26:e5:11:9d:22:2a:df:16:7e:11:ce:
         4c:4e:22:33:79:03:0b:84:13:9c:40:36:3d:cc:9f:a9:04:fe:
         d5:d3:68:82:ad:e9:bc:be:1b:77:ca:b6:9b:f5:97:98:11:8d:
         70:5a:84:cb:88:8c:ce:06:ed:42:12:f7:24:3e:82:ae:5c:bc:
         b3:3d:95:6f:dd:08:2b:27:15:89:3f:61:86:0c:35:e4:d0:9c:
         bc:46:fc:51:95:1c:3b:93:c0:bc:4f:44:d3:65:39:d0:ec:79:
         58:49:16:4a:67:61:7c:29:f8:54:bf:0f:59:f3:18:d7:87:0d:
         2c:40:6c:6e:e3:bf:18:fd:9e:82:19:89:00:33:05:3e:d4:23:
         1a:9b:2a:e3:b5:27:eb:56:98:e1:a3:11:c4:40:c1:81:82:0e:
         59:0e:09:77:30:44:ff:70:52:02:39:c7:82:d0:95:fa:e0:36:
         bb:9c:ee:07:2a:52:b9:49:dc:95:b7:04:4c:a8:f9:6d:df:76:
         cc:78:37:a1:91:6b:17:30:96:9b:7c:f7:15:6a:5f:24:e9:59:
         7d:76:88:b7:b7:99:b3:b3:cc:9b:8e:fb:8c:81:5c:16:27:5c:
         1e:d7:d7:da:e9:a8:f5:05:de:64:a7:74:00:70:f3:e5:35:0d:
         5f:c8:fd:0b:d1:a5:a9:74:c4:c0:a3:35:11:51:42:3d:a7:85:
         e0:81:d1:12:08:14:51:ac:44:93:a3:c3:41:0a:3c:a1:8b:a5:
         37:20:ab:be:c9:c7:c9:b3:16:fe:5b:69:e2:81:5c:a3:fb:e0:
         74:54:21:ab:bf:83:56:ba:35:5e:6d:bc:39:c4:65:9a:70:6a:
         9d:e3:74:c9:92:d4:ac:7c:1d:4b:74:b8:fc:f7:04:af:59:08:
         2b:b9:b4:cc:9f:0d:59:fe:16:64:65:9e:8a:79:e7:e6:c8:0d:
         bb:80:de:c7:84:40:3d:04:f1:f6:a7:80:03:37:c3:8a:11:af:
         7c:81:0b:73:21:58:0a:f1:ff:63:1d:86:fc:fa:93:24:9d:b0:
         05:6e:b5:7f:0c:a4:2a:51:17:60:e4:1e:84:36:0a:46:1d:54:
         ba:46:70:1c:a2:a5:70:cc:6f:b5:76:5c:b2:36:d4:32:9a:23:
         1d:29:a2:9f:ce:10:2e:83:01:75:be:27:37:f4:c3:b1:86:fc:
         2f:04:3d:6e:f7:d7:55:56
```

**Comment by lachellel** [comment]
@ryancdickson 

Received comment on the sample DV certs - 

- Serial Number is greater than 20 octets

**Comment by ryancdickson** [comment]
I had noticed this after the fact when doing ASN1 dumps after posting – but didn’t want to confuse folks with a separate update. The encoding of the serial number generated from RNG (81ffab964c38889ea3e914365228eca1bfcbf8c) pushes the DV cert to 21 octets, despite OpenSSL only presenting 20.

Shall I upload a new set of certs to correct the issue? I’ve got this all automated, so the only time sink involved will be that tied to posting to GitHub.

**Comment by lachellel** [comment]
If it's low effort, please do!  I'm tracking comments received from peer reviews, and this was one.

**Comment by ryancdickson** [comment]
I have the updated sample certs (to include the invalid ones Santosh suggested) at https://github.com/ryancdickson/policies/tree/master/sampleOpenSSLCertificates. 

I emailed Santosh to confirm I understood his request tied to the values in the invalid certs, and once confirmed correct, I'll submit a pull request to merge the updated certs into Master.

Updates:
1 - Corrected serial # length for dv certificate (original cert ended up being 21 after padding)
2 - Added ocsp signing to subordinate CA EKU 
3 - Created 8 new test “invalid” certificates with IPs.
-  One certificate with lowest IP V4 address of 0.0.0.0 for each DV/OV
-  One certificate with highest IP V4 address of 255.255.255.255 for each DV/OV
 -  One certificate with lowest IP V6 address of 0:0:0:0:0:0:0:0 for each DV/OV
 -  One certificate with highest IP V6 address of FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF:FFFF for each DV/OV

**Comment by lachellel** [comment]
- Update the certificate profile to make c=US mandatory.

**Comment by lachellel** [comment]
updated in cebd736

**Comment by fotisl** [comment]
Sorry for my late reply and for reopening this ticket. Currently, the language in the certificate policy regarding the dirnames in the name constraints is:

> For DirectoryName, the Subordinate CA Certificates shall:
> 
> Include at least one DirectoryName in permittedSubtrees specifying c=US

My interpretation is that I am free to generate a SubCA including the following in the permittedSubtress:

```
DirName: C = US
DirName:
```

This satisfies the requirement for at least one DirectoryName (there are two), and for one being C=US. However, the second constraint cancels everything, since it's kind of a 'permit all' constraint.

Furthermore, and this should probably be discussed in a new issue, are you going to restrict the encoding of the subject and the subject alternative names? Per RFC5280:

> CAs issuing certificates with a restriction of the form
> directoryName SHOULD NOT rely on implementation of the full ISO DN
> name comparison algorithm.  This implies name restrictions MUST be
> stated identically to the encoding used in the subject field or
> subjectAltName extension.

**Comment by lachellel** [comment]
- [x] Update to remove "at least one" to be **just/only** the DirName of C=US
