### ISSUE TITLE
Section 4.3.2 Notification to Subscriber

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#51]
In general, the FPKI Device CP should not indicate _No Stipulation_ for any requirement.  Recommend a decision be made as to whether the FPKI requires the CA to notify the subscriber of certificate issuance.  This should be either:
"The CA shall notify the Applicant Representative of certificate issuance."
or
"Notification of certificate issuance is at the discretion of the issuing CA."

**Comment by lachellel** [comment]
@larryfrank had submitted the following for Section 4.3.2:

- The CA SHALL issue the certificate according to the certificate requesting protocol used by the device (this may be automated) and, if the protocol does not provide inherent notification, also notify the authorized organizational representative of the issuance.
