### ISSUE TITLE
Section 3.2.2.4, Validation methods

### ISSUE THREAD

**Issue by debcooley** [uspki/policies#517]
Currently we allow 5, 6, 7, and 10.  

We should delete 5 and 10.  5 is the Domain Authorization Document which is already scheduled to be deprecated in Aug 2018.  10 is TLS certs and is apparently grossly underspecified.

We should add:  method 12.

From version 1.5.7 of the BRs.
"Confirming the Applicant's control over the FQDN by validating the Applicant is the Domain Contact. This method may only be used if the CA is also the Domain Name Registrar, or an Affiliate of the Registrar, of the Base Domain Name.
Note: Once the FQDN has been validated using this method, the CA MAY also issue Certificates for other 
FQDNs that end with all the labels of the validated FQDN. This method is suitable for validating Wildcard 
Domain Names."

That would give us 3 methods total.  sufficient?

**Comment by debcooley** [comment]
I made a pull request for this #518.  No earthly idea how to link this all together....

**Comment by weirdscience** [comment]
We can add a new method but can’t use it until Mozilla updates its policy. Mozilla CP is explicit that they only accept methods 1-10 and not anything past 11 in Version 2.5. No mention to change in version 2.6 draft.

Kenneth Myers
Senior Manager
+1.571.366.6120 Desk
Protiviti | 1640 King Street | Suite #400 | Alexandria | VA 22314 US | Protiviti.com
________________________________

**Comment by weirdscience** [comment]
Section 2.4. I'm working on the gap analysis.

For a certificate capable of being used for SSL-enabled servers, the CA must ensure that the applicant has registered the domain(s) referenced in the certificate or has been authorized by the domain registrant to act on their behalf. This must be done using one or more of the 10 methods documented in section 3.2.2.4 of version 1.4.1 (and not any other version) of the CA/Browser Forum Baseline Requirements. The CA's CP/CPS must clearly specify the procedure(s) that the CA employs, and each documented procedure should state which subsection of 3.2.2.4 it is complying with. **Even if the current version of the BRs contains a method 3.2.2.4.11, CAs are not permitted to use this method.**

**Comment by konklone** [comment]
Closed by #518.
