### ISSUE TITLE
Section 1.1.3.2 - Subscriber Certificates | Why is OCSP a Subscriber Cert?

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#519]
The CP lists an OCSP certificate as a subscriber certificate. By the definition in the CP, a subscriber certificate is both a legal entity named in the subject and that has a terms of use or subscriber agreement. OCSP is not named in the baseline requirements as a subscriber certificate.

I recommend we create a new infrastructure certificates type which includes OCSP responder certificates. This saves us from addressing subscriber type requirements for certificates that are only issued in support of the CA by trusted roles.

**Comment by lachellel** [comment]
WRT this issue and PR #520: 

- [ ] Section 7.1.6.4 requires an update

**Comment by weirdscience** [comment]
I took out the OCSP cert reference in 7.1.6.4 and added to a new section 7.1.6.5 Infrastructure certs. What other update is missing?

**Comment by lachellel** [comment]
Infrastructure certs = agreed upon.  
Need to update the profiles **and** check all of Section 4.

**Comment by lachellel** [comment]
closed in #520
