### ISSUE TITLE
Section 4.4.2 Publication of the certificate by the CA

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#53]
Again - recommend the FPKI decide whether it will publish certificates, under what circumstances it might not publish, etc. and make this statement here.

**Comment by lachellel** [comment]
Agree...this is one of the sections where discussion of CT Logs and requiring writing to CT Logs is needed.  Need verbiage

see #37

**Comment by lachellel** [comment]
CT will go into 4.4.3

Verbiage for 4.4.2?  
discussion is that "No stipulation" to be "No requirement".

**Comment by lachellel** [comment]
No stipulation stands...

**Comment by jaspenc** [comment]
This CP governs the Device Root as well as sets requirements for subordinates, is that right?  So the Device Root CA (or the individuals running it) can choose to publish some certificates and not publish others?  I can see allowing subordinate CAs to publish or not, but the device root should do one or the other.

**Comment by LarryFrank** [comment]
Added to 4.4.2

CAs SHALL publish all Subscriber TLS certificates in 2 Certificate Transparency Log servers.

**Comment by lachellel** [comment]
The final recommendation was to include in both sections.  Updates will be made.
