### ISSUE TITLE
left hand navigation not working

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#532]
On the preview and live site, the left hand navigation isn't linking for the numbered sections.  Check these configs:

- https://github.com/uspki/policies/edit/master/02-policy-page.md

**Comment by ryancdickson** [comment]
I think it might be the "." (period character).

Appendices link without issue.

I'll look into this.

**Comment by ryancdickson** [comment]
@lachellel - whenever you have time, any chance you could please escalate my privs. such that I can create a new branch in an effort to test updates/use Federalist Live Preview?
