### ISSUE TITLE
CP v1.x Change Proposal:  Add CT requirements back to the CP and CPS for Public Trust PKI

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#539]
- Version 0.2 of this Certificate Policy explicitly included the Certificate Transparency (CT) requirements
- Version 0.3 (draft) removed the requirements due to the "chicken/egg" challenge with audits, and a new root

A change proposal to add the CT requirements back to the CP and required CA practices needs to be created.  Please reference this commit (c7e44c8) to help with the change proposal.

**Comment by idmken** [comment]
Noted.
