### ISSUE TITLE
Section 4.4.3  Notification of certificate issuance by the CA to other entities

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#54]
Recommend this is N/A, unless FPKI Device Root is required to notify any third party when a certificate is issued, in which case describe that here.

**Comment by lachellel** [comment]
Agree...this is one of the sections where discussion of CT Logs and requiring writing to CT Logs is needed.  Need verbiage

see #37

**Comment by lachellel** [comment]
closing in favor of #37
