### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by debcooley** [uspki/policies#550]
Even though all the Certificate Transparency has been removed from the CP the definitions remain.  I can go either way on this:  
1.  definitions are harmless enough - obviously there is no requirements language in a definition.  
2.  It will make it easier to add the CT information back in.

But it looks funny.  Is that a reason to remove them?  dunno....

hence I'm writing an issue vice a pull request....

**Comment by techliaison** [comment]
My 2 cents - I would leave the definition.  We still have the SCT as optional in the serverAuth certificate profiles, so I view the definition of CT as potentially useful information even if it is not currently required.

**Comment by lachellel** [comment]
i think we agreed to leave the definition in!  closing..
