### ISSUE TITLE
Review NSR Ballot SC03 - Two Factor Authentication and Password Improvements

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#554]
SC3 Ballot: https://cabforum.org/2018/08/16/ballot-sc3-two-factor-authentication-and-password-improvements/

SC3 Github: https://github.com/cabforum/documents/commit/4a98c0917510937432d1f004cf36fd989851cdb8#diff-50fc941f7be640a0bf58764b83d5d9e7

Looks like four new additions to the NSR and we've incorporated the NSR in the CP. The section interpretation is our own because the NSR is not in a RFC 3647 format.

- [x] Group accounts or shared role credentials shall not be used. 

- Good. CP Section 5.2.3 "All trusted roles shall use a unique credential created by or assigned to a single individual for identification and authentication."

- [x] Revised password requirements for trusted role access using a username or password.

- Good. Both the Root and Issuer CPS require MFA for all trusted roles. Possibly consider updating CP to match MFA reference in CPS or add password requirements to keep it flexible and compliant. CP Section 5.2.3 "CAs shall implement multi-factor or multi-party authentication for all Administrator trusted role access to Certificate System Components including operating system and software."

- [x] Have a policy (vice require) for log out or lock when a workstation is no longer used.

- Potential CP update. No CP or CPS reference of an inactivity log or lock. Only related to failed access attempts. CP 6.6.2 "All system accounts and trusted role accounts shall have be configured to lockout access after five (5) failed access attempts"

- [x] Have a procedure to configure (vice just configure) inactivity time-outs.

- Potential CP update. Same as above. May not need to update CP if both root and issuer have an SOP to configure inactivity time-outs.

**Comment by weirdscience** [comment]
These were integrated into CP v0.4.

**Comment by weirdscience** [comment]
Retract last statement. Did not make it in the v0.4.

**Comment by lachellel** [comment]
I caught these in https://github.com/uspki/policies/commit/28cea4208b3eef975f0c6f20bf352b5f7da9fa8b

For a statement that says "have a policy" - USG has many policies including those defined and governed by DoD, NIST, OMB, DHS (govt wide), and other Agency level.  As a practice, CA operator teams should not be develop/write local policies and can reference an existing govt policy.

**Comment by weirdscience** [comment]
Looks like ready to close.
