### ISSUE TITLE
CAA Record Generator or Profile

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#557]
It might be useful to have a CAA record generator playbook. It would help agencies that use CAA to add the new federal TLS CA to the record. We could either point to a generator or have a CAA profile for agencies to follow.

https://caatestsuite.com/ - CAA Test Suite for CAs
https://sslmate.com/caa/ - CAA Record Generator

**Comment by cryptofilegsa** [comment]
And once CAA records are generated for government domains it would be of course useful for all PKI issuances to be checked against not only commercial CAA records, but also any government issued ones.

**Comment by lachellel** [comment]
Marking this as "on hold"...
No impact or change for the **Certificate Policy** or the development and testing of the CAs

We do need to gather the suggestions for content to include on the website for the CP, CPS, Audits and tools and resources for the agency teams.

**Comment by idmken** [comment]
Noted.
