### ISSUE TITLE
Section 4.5.2 Relying party public key and certificate usage

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#56]
While it is generally true that we can't control the actions of the relying parties, we should at least set expectations.  Recommend a statement be included here that sets expectations: e.g. not trusting certificates when used in situations for which they were not intended (violate basic constraints on key usage/extended key usage); verifying validity prior to trusting certificates; etc.

**Comment by lachellel** [comment]
@larryfrank has submitted: 

- Certificates may specify restrictions on use through critical certificate extensions, including the basic constraints and key usage extensions.  All CAs operating under this policy shall provide revocation information.  It is recommended that relying parties process and comply with this information whenever using certificates in a transaction.
