### ISSUE TITLE
Update maintainers in README

### ISSUE THREAD

**Issue by IanLee1521** [uspki/policies#561]
I'm not positive on what the right answer is, hence the issue rather than a PR, but I suspect we want to update the [Maintainers in the README](https://github.com/uspki/policies/blob/master/README.md#maintainers) to remove @konklone 's gsa.gov email. 

Not sure if it will just be @lachellel going forward, or if there is an / are alternate contacts.

**Comment by ryancdickson** [comment]
Hi @IanLee1521,

Thanks for your comment. I've removed @konklone's contact information from the README in our most recent branch.

Thanks again,
Ryan

**Comment by IanLee1521** [comment]
Thanks! (Solved by d674d7e)
