### ISSUE TITLE
Policy Document Naming Consistency

### ISSUE THREAD

**Issue by ryancdickson** [uspki/policies#568]
**Nitpick**:

We lack standardization on key terms in policy document titles (e.g., "_U.S._" vs. "_United States_", "_Certification Practice Statement_" vs. "_Certificate Practices Statement_", "_CA_" vs. "_Certificate Authority_" (vs. "_Certification Authority_"):

- **CP**: U.S. Federal Public Trust TLS PKI Certificate Policy 
- **Root CPS**: United States Federal PKI X.509 Certification Practice Statement (CPS) for the U.S. Federal TLS - Root Certificate Authority
- **Issuing CA CPS**: U.S. Federal Public Trust TLS PKI Defense Information Systems Agency Subordinate CA Certificate Practices Statement

<br>

**Possible Solutions:**
- **CP**: U.S. Federal Public Trust TLS PKI Certificate Policy (_no change_)
- **Root CPS**:  U.S. Federal Public Trust TLS PKI Root CA Certification Practice Statement
- **Issuing CA CPS**: U.S. Federal Public Trust TLS PKI Subordinate CA Certification Practice Statement

<br>

**Comparisons:**
- Internet Security Research Group (ISRG) **Certification Practice Statement** (Let's Encrypt)

**Comment by weirdscience** [comment]
RFC 5280 calls out CPS as a certification practice statement. Including x.509 narrows the focus to public key certificates unless the group will use these for things other than x509 certificates.

**Comment by idmken** [comment]
Noted.
