### ISSUE TITLE
4.9.1.1  Reasons for revoking a subscriber certificate

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#58]
Recommend adding "“when the binding between the subject and the subject’s public key defined within a certificate is no longer considered valid (e.g. identifying information in the certificate is no longer valid)”
Item 13 - this is a non-sequitur.  The CA cannot revoke a certificate issued by a subordinate CA.  It can revoke the subordinate CA.  Revocation of CA certificates is handled in Section 4.9.1.2.  
If the intent is that revocation of a subordinate CA for the reason of compromise occurs in 24 hours, then rephrase item 13, or rename the section.

**Comment by jaspenc** [comment]
On this same subject in Section 4.9.1.2, Item 3 states: The Issuing CA obtains evidence that the Subordinate CA's Private Key corresponding to the Public Key in the Certificate suffered a Key Compromise or no longer complies with the requirements of Sections 6.1.5 and 6.1.6.  This appears to relate to 4.9.1.1 Item 13.
Recommend 7 days (as designated in Section 4.9.1.2) is too long for a CA key compromise situation, particularly when a subscriber key compromise is 24 hours and has far less potential to inflict damage.

**Comment by jaspenc** [comment]
Section 4.9.12 currently references Section 4.9.1 which indicates 24 hours for subscriber certificates and 7 days for CA certificates.   
Recommend revising this section, at least to indicate that a CA that suffered key compromise must be revoked within 24 hours.

**Comment by lachellel** [comment]
> Item 13 - this is a non-sequitur. The CA cannot revoke a certificate issued by a subordinate CA. It can revoke the subordinate CA. Revocation of CA certificates is handled in Section 4.9.1.2.
If the intent is that revocation of a subordinate CA for the reason of compromise occurs in 24 hours, then rephrase item 13, or rename the section.

I think this does need to be made a bit more clear for the audience. 

In this scenario (subscriber revocation) -, I believe item 13: 

> The CA is made aware of a possible compromise of the Private Key of the Subordinate CA used for issuing the Certificate;

is specifically for the CA to revoke all the subscriber certs if "the CA is made aware of possible compromise...anywhere in the chain used for issuing the Certificate"...

To address browser behaviors such as OneCRL and CRLSets...**revocations in the chains** aren't always processed for end entity certs based on the browsers and speed, OS, push/pull, bandwidth, etc...

@konklone how do you read this?

**Comment by lachellel** [comment]
![revocation_scenario](https://cloud.githubusercontent.com/assets/6501821/22087451/00b6fe8c-ddac-11e6-921e-be1e209c0db4.png)

my poor diagram attempting to show the logic

The suggestion is: 

- Make revocation == 24 hours for both

**Comment by konklone** [comment]
> To address browser behaviors such as OneCRL and CRLSets...revocations in the chains aren't always processed for end entity certs based on the browsers and speed, OS, push/pull, bandwidth, etc...

That's right. To get reliable revocation of non-end-entity certificates that represent significant risk to end users, the PKI will -- in addition to any ordinary revocation-- need to report such revocations directly to browser/OS vendors so they can blacklist them using their preferred methods.
