### ISSUE TITLE
Frequently Asked Questions (FAQs): What and Why?

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#582]
Starting a list of frequently asked questions.  Audience is US **federal** government teams.  

- **Purpose**:  Add a short lived FAQ to the website or (alternately) a short lived presentation for federal government teams to review 
-  Some questions are intentionally meant to be humorous
-  Please add more questions 

**************
- What is a certificate policy? 
- What is the difference between a _certificate policy_ and a Policy in government?
- Will each agency have their own certification authority for public trust pki?
- What is the difference between Public Trust PKI versus the current Federal PKI?
- Who defines the rules for Public Trust PKI?
- Why can't US government tell the trust store programs to let us do whatever we want?
- What is Man in the Middle (MiTM)? Will this certification authority be used for Man in the Middle?  
- When will this service be available?
- Will we be required to use this service?
- I don't want to automate - I like forms! What should I do?
- Can US states and locals (using .gov or not) get a certificate from PT PKI?
- Will the PT PKI operate its own Certificate Transparency log?
- What’s the cost to obtain a certificate?
- How will someone prove they are authorized to obtain a PT PKI cert?

@h-m-f-t open and transparent?  :+1:

**Comment by michaelblyons** [comment]
Can Legislative and Judicial entities get certificates and/or become sub-CAs?

**Comment by idmken** [comment]
Noted for future help desk page.
