### ISSUE TITLE
CAB Forum Ballot SC16: Other Subject Attributes

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#585]
I didn't see if this ballot was incorporated.

This ballot intends to clarify requirements placed on Subject attributes in Subscriber certificates in BR section 7.1.4.2. Specifically, Subject fields must contain more than just metadata if they are present in a certificate.

Exact text

- [ ] Section 7.1.4.2 | Subject attributes MUST NOT contain only metadata such as ‘.’, ‘-‘, and ‘ ‘ (i.e. space) characters, and/or any other indication that the value is absent, incomplete, or not applicable.

**Comment by weirdscience** [comment]
I think we are good to not make an update based on this line "CAs shall not include a Domain Name in a Subject attribute except as validated under Section 3.2.2.4."

Can someone second this to close with no change?

**Comment by idmken** [comment]
Incorporated into future CP update.
