### ISSUE TITLE
Section 3.2.2.6 Wildcard Domain Validation

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#589]
- The second paragraph in Section 3.2.2.6 is inconsistent and could cause confusion to readers.
- The current text in this CP represents text from an older CA/B Forum Requirements.  
- The current text reads as if we allow those domain validation methods (example validation method 3.2.2.4.5) when we have specified those validation methods as not allowed in this CP.

**Comment by idmken** [comment]
Incorporated into future CP update.
