### ISSUE TITLE
Section 4.9.2 Who can request revocation

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#59]
For the FPKI Device Root, should the FPKIPA or other governing body be identified as authorized to request revocation?

**Comment by lachellel** [comment]
Draft in section4 branch:

- https://github.com/uspki/policies/blob/section4/certificate-policy.md#4912-reasons-for-revoking-a-subordinate-ca-certificate

Added to 10

> The technical content or format of the Certificate presents an unacceptable risk to Application Software Suppliers or Relying Parties (e.g. the **FPKI Policy Authority** or CA/Browser Forum might determine that a deprecated cryptographic/signature algorithm or key size presents an unacceptable risk and that such Certificates should be revoked and replaced by CAs within a given period of time)

**Comment by lachellel** [comment]
Should it be stated explicitly in an addition (add 11 to the list)?

**Comment by LarryFrank** [comment]
> For the FPKI Device Root, should the FPKIPA or other governing body be identified as authorized to request revocation?

Right now - says "The PMA SHALL direct any revocation of a CA certificate."

**Comment by lachellel** [comment]
#137 
ready for close
