### ISSUE TITLE
Section 5.5 - NARA Archive Requirements

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#591]
Comment on Section 5.5 

_In addition to the archive requirements specified in this CP, archive procedures shall follow either the General Records Schedules established by the National Archives and Records Administration (NARA) or an agency-specific general records schedule as applicable._

- Why would an agency specific general records schedule ever be applicable?

- @lachellel additional comments - is this a valid requirement in the first place?  The requirement was taken from common policy, but the requirement may not be fully valid.  The NARA requirements were driven in part by legally binding digital signatures or human (person) authentication events for engaging in some government transactions (forensics and legal purposes in federal courts).

**Comment by idmken** [comment]
Incorporated into future CP update.
