### ISSUE TITLE
Remove SHA-512? 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#593]
Comments received (DoD): 
- Section 6.1.5:  Remove SHA-512 from subscriber certificate allowed digest algorithms. 
- Section 7.1.3:  Remove SHA512RSA for signing.

See discussion in #578

**Comment by ryancdickson** [comment]
Comments received (Treasury):
- 6.1.5 - Remove SHA-512 from subscriber cert allowed digest algorithms since P521 was not included in the ECC curves allowed. 
- 7.1.3 – realistically, could remove SHA384RSA and SHA512RSA for signing…  none of the profiles use them.  All specify SHA256RSA.

**Comment by idmken** [comment]
Incorporated into future CP update.
