### ISSUE TITLE
RA Verbiage - Confusing? 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#594]
Comment received (DoD): 

- Section 1.3.4:  Replace, “This policy prohibits persons who may not be affiliated with the same U.S. Federal Government organizational unit that is operating the CA to assist in the certificate application or domain validation process” with something more clear.  Perhaps a statement that RAs are not used in this system.

**Comment by ryancdickson** [comment]
Similar comments offered from Treasury:

- 1.3.4 - Change the language in Para - “persons who may not be affiliated”
    -  To: “This policy prohibits persons who are not be affiliated with the same U.S. Federal Government organizational unit that is operating the CA to assist in the certificate application or domain validation process.”

**Comment by idmken** [comment]
Incorporated into future CP update.
