### ISSUE TITLE
Process for incorporating initial comments and changes?

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#6]
@techliaison  @weirdscience @tkpk @konklone 

without over-engineering, I wanted to start some additional pull requests which incorporate the basic additions that you had drafted.  Includes: 
- Section 1:  Updating the Authority, who owns the doc, who owns the process, etc
- Section 2:  Publication and Responsibility 
- Section 3:  Identity and Authentication

Rather than having a single PR with too many changes that apply to different sections - why not separate branches for each section (1, 2, 3) to start?  

Not long term proposal!  Just to jumpstart applying proposed updates to each section...

thoughts?

**Comment by weirdscience** [comment]
That works and if needed just merge the sections together later if needed. Depending on the number of people, add a page for each CP section and have at it. Some sections will be developed quicker than others.

**Comment by lachellel** [comment]
It's one markdown file (/policies/certificate-policy.md) for the CP.

three branches have been added to hold changes for Section 1, Section 2 and Section 3

**Comment by LarryFrank** [comment]
Staring in Section 1.1 - remove text starting at "**Notice to Readers**" to the end of the paragraph - this is boiler plate from the CA/B Forum and not applicable for an operational CP.
Remove Section 1.2.1 - which is the CA/B forum Revision history.
Remove Section 1.2.2 Relevant dates - also only applicable to CA/B forum version.  CP should state the requirements.
Consider pulling the appropriate sections for the Fed Bridge CP (or Common) to replace all of Section 1.3., 1.4 and 1.5.
