### ISSUE TITLE
Section 4.9.3 Procedure for revocation request

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#60]
Since the FPKI Device Root is the CA cited in this section, it must respond to this requirement not repeat it.  Recommend using FPKI COMMON language (at a minimum):  
"A request to revoke a certificate shall identify the certificate to be revoked, explain the reason for revocation, and allow the request to be authenticated (e.g., digitally or manually signed). The steps involved in the process of requesting a certification revocation are detailed in the CPS."

**Comment by LarryFrank** [comment]
Left the BR text (which is largely non-requirements)  and added "A request to revoke a certificate shall identify the certificate to be revoked, explain the reason for revocation, and allow the request to be authenticated (e.g., digitally or manually signed). The steps involved in the process of requesting a certification revocation are detailed in the CPS"

**Comment by lachellel** [comment]
#137 
ready for close
