### ISSUE TITLE
CAB Forum Ballot SC19: Phone Contact with DNS CAA Phone Contact v2

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#611]
May need to add a Method 17 and state it is not used.

https://cabforum.org/2019/05/21/ballot-sc19-phone-contact-with-dns-caa-phone-contact-v2/

Purpose of Ballot: This ballot will permit domain owners to publish phone numbers in a DNS CAA record for the purposes of performing domain validation.

**Comment by idmken** [comment]
Incorporated into future CP update.
