### ISSUE TITLE
CAB Forum Ballot SC21 - NSR section 3 (Log Integrity Controls)

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#614]
https://cabforum.org/2019/10/04/ballot-sc21-the-network-and-certificate-systems-security-requirements-section-3-log-integrity-controls/

Purpose of Ballot

The Network and Certificate System Security Requirements committee is proposing this ballot to revise the current requirements to better allow for automation and continuous monitoring of systems. The goal of this ballot is to remove manual efforts that can be less effective and more resource-intensive than automated monitoring and alerting.

This ballot also adds specific requirements in terms of the timeliness for addressing alerting from automated monitoring and alerting to ensure the implementation of automation does not increase the length of time that a potential issue could go without being detected.

It is proposed by Ben Wilson of DigiCert and endorsed by Trevoli Ponds-White of Amazon and Fotis Loukos of SSL.com to revise the Network and Certificate System Security Requirements (Requirements) as set forth in the following language of Section 3 of the Requirements, to be EFFECTIVE  ninety (90) days after completion of the IPR Review Period:

*— BALLOT BEGINS —*

e.        Monitor the integrity of the logging processes for application and system logs through continuous automated monitoring and alerting or through a human review to ensure that logging and log-integrity  functions are effective. Alternatively, if a human review is utilized and the system is online, the process must be performed at least once every 31 days.

f.        Monitor the archival and retention of logs to ensure that logs are retained for the appropriate amount of time in accordance with the disclosed business practices and applicable legislation.

g.        If continuous automated monitoring and alerting is utilized to satisfy sections 1.h. or 3.e. of these Requirements, respond to the alert and initiate a plan of action within at most twenty-four (24) hours.

*— BALLOT ENDS —*

- [ ] CP does/does not need update.
- [ ] Root CPS does/does not need update.
- [ ] Issuer CPS does/does not need update.

**Comment by idmken** [comment]
Incorporated into future CP update.
