### ISSUE TITLE
Section 4.9.5 Time within which CA must process the revocation request

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#62]
A certificate problem report is defined as "Complaint of suspected Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, or inappropriate conduct related to Certificates."  
It does not appear that a Certificate Problem Report is the same thing as a revocation request?  Is it authoritative?  Or does it lead to a revocation request?  The existing statement describes processing a certificate problem report, but doesn't address the timing for revocation.  FPKI should set a time-certain for the revocation of a certificate once a revocation request has been received.  The CP already requires 24 hours and 7 days in Section 4.9.1.  For this section, I recommend the statement is made that revocation requests should be processed before next CRL is issued (exception for situations where CRL issuance is imminent, e.g. within 2 hours).

**Comment by LarryFrank** [comment]
Changing the first sentence to read "The CA SHALL begin investigation of a Request for Revocation or a Certificate Problem Report immediately upon receipt, and decide whether revocation or other appropriate action is warranted based on at least the following criteria"  Frankly, this is telling the CA how to suck eggs - but this reflects the BR text (which I don't particularly like but don't really care. )  Important words are "begin investigation... immediately".

**Comment by lachellel** [comment]
#137 
ready for close
