### ISSUE TITLE
Repo retirement/public archive

### ISSUE THREAD

**Issue by maxwellfunk** [uspki/policies#631]
@idmken 

we received a request at the FPKIPA meeting this month to archive this repo as the MA team may not utilize it in the next update iteration for CA/B updates.  it should still be viewable/accessible I believe, but it may not be used for policy updates moving forward. 

@techliaison for awareness

**Comment by idmken** [comment]
Will do. Is that take down the website, update references, and make this a public archive?

**Comment by maxwellfunk** [comment]
we may want to wait until the next version is approved/published before we take down the current sub-domain (devicepki.idmagement.gov), but once the new version is available we probably only require the public archive of the repo for version archive purposes.  The MA team will have to weigh in, but expect them to host the CP on the fpki.gov or pki.gov domain (wherever the new public repositories for the public trust pki will be).
