### ISSUE TITLE
Section 4.9.10 On-line revocation checking requirements

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#64]
The opening phrase "Effective 1 January 2013" is not needed.  The date has passed.  Ditto the opening phrase in the 7th paragraph.
In the 6th paragraph - recommend the SHOULDs be replaced with SHALLs.

**Comment by lachellel** [comment]
draft under section4 branch:

- https://github.com/uspki/policies/blob/section4/certificate-policy.md#4910-on-line-revocation-checking-requirements

Dates were removed. 

6th paragraph: 

> If the OCSP responder receives a request for status of a certificate that has not been issued, then the responder SHOULD NOT respond with a "good" status. The CA SHOULD monitor the responder for such requests as part of its security response procedures.

change to SHALL?
