### ISSUE TITLE
Section 4.9.13 Circumstances for suspension

### ISSUE THREAD

**Issue by jaspenc** [uspki/policies#65]
We can infer from the statement concerning the repository that certificate suspension is not permitted.  
It would be better that this section makes the definitive statement that suspension of certificates is not permitted.

**Comment by lachellel** [comment]
Draft under section4:

- https://github.com/uspki/policies/blob/section4/certificate-policy.md#4913-circumstances-for-suspension

> Certificates issued under this policy SHALL NOT be suspended.
