### ISSUE TITLE
7.1.2.2 Subordinate CA and Certificate Policies extension marked as critical? 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#67]
BRD:  
- https://github.com/uspki/policies/blob/master/certificate-policy.md#7122-subordinate-ca-certificate

a. certificatePolicies

> This extension MUST be present and SHOULD NOT be marked critical.
> 
> certificatePolicies:policyIdentifier (Required)

**Comment by lachellel** [comment]
There is a recommendation on the table to change to: 

a. certificatePolicies

> This extension SHALL be present and **SHALL** be marked critical.
> 
> certificatePolicies:policyIdentifier (Required)

**Comment by mttcpr2** [comment]
I don't think cert policies should be marked critical. If we want to require policy processing then I think the right thing to do is set requireExplicitPolicy in the policy constraints extension and mark that extension critical.

**Comment by lachellel** [comment]
#75

Referencing profile drafts first for discussion and comments

- certificate-profile-subordinate-CA.md
