### ISSUE TITLE
Wrong license listed for BRs

### ISSUE THREAD

**Issue by pzb** [uspki/policies#7]
The CA/Browser Forum documents are at a minimum licensed under CC-BY. ("This  work  is  licensed  under  the  Creative  Commons  Attribution  4.0  International  license.")

Further, each contributor to the CABF documents has agreed to  "license to all, worldwide, whether or not they are CAB Forum Participants to reproduce, distribute, make derivative works and display" the documents.

So CC-ND is never in play.

**Comment by konklone** [comment]
Whoops, thanks for catching that -- not sure we listed it as CC-BY-ND when it's just CC-BY. CC-BY-ND would prevent anyone from using it to make CPs, after all. :)
