### ISSUE TITLE
4.7.1 length of time for a rekey and new identity proofing

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#70]
What is the maximum time allowed between identity proofing events, in relation to a rekey?

**Comment by LarryFrank** [comment]
> What is the maximum time allowed between identity proofing events, in relation to a rekey?

Right now the text says "if it has been less than 9 years "  BR says "No Stipulation" so right now this is "complaint" .

**Comment by lachellel** [comment]
Still open - the 825 day debate...

Bump...

**Comment by LarryFrank** [comment]
I thought we closed this - the result being no "rekey"...  The discussion on 825 indicated that the "current" certificate was NOT considered valid for requesting a new one - so really rekey )all of 4.7) is "not applicable" .  Needed to go through (whatever process) as for initial issuance every time so the CA was forced to relook any data used for validation.  Happy to NOT have that be the answer but not trying to re-open previous discussion/decisions.

**Comment by lachellel** [comment]
+1

I can open another issue for the 825 days and cross reference.  This one is ready for close.

**Comment by LarryFrank** [comment]
> I can open another issue for the 825 days and cross reference. This one is ready for close.

Don't on my account - don't LIKE the answer but agree it is what the CA/B forum people want.

**Comment by lachellel** [comment]
for @konklone comment on limiting down to less than 825 days...on the PR...
