### ISSUE TITLE
OCSP signing certificates lifetime and renewal

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#71]
**What should the OCSP certificate lifetimes (max) be?** 

- Section 6.3.2 needs to be updated to include OCSP signing certificates and lifetime (max)
- Section 4.6.1 and renewals specific to OCSP signing certs to be aligned

**Comment by lachellel** [comment]
#75 

Reference profiles first for discussion and comments

- certificate-profile-OCSP-responder.md

**Comment by lachellel** [comment]
@mttcpr2 @techliaison

There are mismatches in OCSP versus Subscriber certificates - throughout Sections 4 and Section 6.  

For ease of auditing, compliance, **and** operations: 

- Should we add OCSP Certificates as specifically identified in all areas - including protection of keys, etc? 
- OR, should we add OCSP Certificates as a sub-set of Subscriber certificates with inheritance of all policy not explicitly stated otherwise? 

I don't readily see a good example from CPs and CPSs.  If you find one, feel free to link here.

**Comment by mttcpr2** [comment]
@lachellel 

I think the best practice is to call out the OCSP Responder as a Certificate Status Authority (CSA). Controls in most respects should be on par with the CA. The CertiPath CP is an example http://certipath.com/FederatedTrust_PolicyManagementAuthority.html
