### ISSUE TITLE
Server Authentication Certificate Profile

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#80]
Tracking updates and notes for server auth cert profile

**Comment by lachellel** [comment]
Serial Number:
- Add octets

Validity Period: 
- Open issue for "13 month" discussion, and CA/B ballot item

Subject Distinguished Name:
- Printable string
- CN is not used (on its way out) by the technology itself
  - however, we might want to still include it for stakeholders in non-browser
  - **option 1**: Mandatory, must match the first FQDN in the subject alt name
  - **option 2:** completely remove (align with the deprecation) and flush out all the client libraries that are still dependent 
  - **option 3**: recommended to not be included except for specific use cases (that can be deprecated over time)

  - TLD restricted to .mil and .gov

AKI: 
- Update with other profiles
- reference 5280 for the hash and how it's derived
 
Basic Constraints: 
- reference CA/B Forum
- Update to mandatory

SKI: 
- Update with other profiles
- reference 5280 for the hash and how it's derived

EKU: 
- Mark "Mandatory"

Policy OIDs:
- potentially make policy URI mandatory (good practice) and reference to the 

SAN: 
- Mandatory
- FQDN
- Add information 
- Do not allow RFC822 email in SAN?  Open Issue to discuss

AIA: 
- Update to align with other profiles verbiage
- Explicitly say LDAP not allowed
- reference https loophole / recursiveness issue

Name Constraints: 
- Make not allowed

Issuer Alt Name: 
- Make not allowed

Private Extensions: 
- Do we make "not allowed"?
- If allowed, must be approved by PA

Transparency Information: 
- Review; good first pass

**Comment by dcooper16** [comment]
Hi,

I was just looking at the server authentication certificate profile and noticed that is says:

> Public exponent must be an odd integer ≥ 3 (recommended that it be between 216+1 and 2256-1.)

(I assume it means "between 2^16+1 and 2^256+1)

Section 6.1.6 of the certificate policy says the same thing:
> RSA: The CA SHALL confirm that the value of the public exponent is an odd number equal to 3 or more. Additionally, the public exponent SHOULD be in the range between 2^16+1 and 2^256-1.

Appendix B.3.1 of [FIPS 186-4](https://doi.org/10.6028/NIST.FIPS.186-4) says that "The exponent _e_ **shall** be an odd positive integer such that:
* 2^16 < _e_ < 2^256.

Since the [FIPS 186-4](https://doi.org/10.6028/NIST.FIPS.186-4) requirement is consistent with the Baseline Requirement's recommendations, I would suggest changing the profile's requirements to match those of [FIPS 186-4](https://doi.org/10.6028/NIST.FIPS.186-4).

**Comment by dcooper16** [comment]
nameConstraints:

> If present, any combination of permitted and excluded subtrees may appear. If permitted and excluded subtrees overlap the excluded take precedence.
> Permitted dnsNames should be included.
> IP addresses should all be excluded.

This needs to be removed. The nameConstraints extension cannot appear in an end-entity certificate.

**Comment by lachellel** [comment]
thanks @dcooper16

when we were translating from docs to markdown, I probably made **more** than one big gaffe.   We'll include these in the PRs.

**Comment by lachellel** [comment]
Will open new issue to align all profiles, including extensions and markdown tables

All items in this issue have been addressed
