### ISSUE TITLE
OCSP Responder Certificate Profile Comments

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#86]
include comments for the ocsp certificate profile here

**Comment by lachellel** [comment]
Serial Number:
- Add octets

Issuer Distinguished Name: 
- clarify wording so it doesn't appear as if a CA is an "OCSP Responder Issuing CA"

Validity Period:
- UTC and generalized time needs to be updated

Subject DN:
- make clear that it should note the cert is specific to the OCSP responder
- remove the Domain Component Names

Subject Public Key Information: 
- make fixes same as subscriber profile
- limit to RSA
- open question on ECC for ocsp
  - review RFC for any explicit reqts - does the OCSP signer cert need to match the issuing CA or the end entity certs (ECC vs RSA)

AKI: 
- update to more clearly specify the RFC for the sha-1 hash derivation 

basicConstraints:
- check BRD (Section 7.1.2.x)
- if needed update OR remove entirely 
- not used for portions of current FPKI and OCSP signers

SKI:
-  update to more clearly specify the RFC for the sha-1 hash derivation

Key Usage: 
-  keep as is

EKU: 
- Mark Mandatory
- does it need to be marked as critical

Certificate Policies: 
- Required Policy Fields - has to include all the certificate policies for all certificates issued by the Issuing CA which the OCSP responder responds for

SAN: 
- determine if it should be Not Permitted or Not Recommended

AIA: 
- Update with verbiage aligning to other three profiles
- can be single certificate (not the CMS certs only)
- how do we apply this to the Root CA (and the OCSP responder) - one example is no AIA, another example is for cross-cert
- look up specifics on / ask open questions

CDP: 
- look at CA/B Forum specifics that would allow (optional)
- why would we need this?  


For all extensions: 
- Add all of the same extensions in all the profiles
- Explicitly mark Not Used consistently
- if there is an extension that is Not Used for all profiles, then don't list it at all

**Comment by mttcpr2** [comment]
Regarding EKU criticality, I would say yes. The OCSP responder cert should not be used for any other purpose and OCSP clients are obligated to check EKU for id-kp-OCSPSigning by the RFC.

**Comment by lachellel** [comment]
For: 

> basicConstraints:
> 
> check BRD (Section 7.1.2.x)
> if needed update OR remove entirely
> not used for portions of current FPKI and OCSP signers


Specified as "optional" in BRD.  

Updating in commits / pr to mark as "not present" in OCSP certificate profile for this CP.

**Comment by lachellel** [comment]
For 

> SAN:
> 
> determine if it should be Not Permitted or Not Recommended


when would a SAN be a good idea for an OCSP responder certificate? 

Marking as Not Permitted for first draft.

**Comment by lachellel** [comment]
For 

> AIA:
> 
> Update with verbiage aligning to other three profiles
> can be single certificate (not the CMS certs only)
> how do we apply this to the Root CA (and the OCSP responder) - one example is no AIA, another example is for cross-cert
> look up specifics on / ask open questions

Open new issue

**Comment by mttcpr2** [comment]
AIA - what motivated not using certs only p7c?  Almost all (98% of those we have under monitoring) AIA links I've seen are p7c. I recommend all the AIA links be p7c unless there is some compelling reason to not do so.

SAN -  I would advocate including OCSP Responder URL. Nothing else in the cert tells you where the thing lives.

CDP - No reason to include CRL DP when including id-pkix-ocsp-nocheck

**Comment by lachellel** [comment]
Review https://github.com/uspki/policies/labels/Section%206
for updates and inclusion as needed
