### ISSUE TITLE
CRL Certificate Profile Comments

### ISSUE THREAD

**Issue by TLSrUS** [uspki/policies#87]
CRL Certificate Profile Issue #87 - notes from 2/16/17 call

nextUpdate

- Language will match the language for date format in the other profiles; Sect 4.9.7 defines the interval

Issuer Signature

- Match whatever algorithm the issuer CA algorithm uses; we should ask the question if we should specify ECC 

Authority Key Identifier

- We will not use different keys with the same name; this comment should go in Section 5.6

Reason Code

- May be a potential concern because it may deviate from CAB Forum requirements; we need to check if this is CAB forum requirement before we include it, though Para 7.2.2 or 4.9 is empty; we also need to look at additional requirements that other trust stores may require.

Hold Instruction

- Change to "not allowed”; check to see if this is a requirement

Issuing Distribution Point

- Change to "not allowed”; delete text in Value field

##

**Comment by grandamp** [comment]
Reason Code

- [Chrome makes use of CRLSets](https://dev.chromium.org/Home/chromium-security/crlsets), which appear to be formed by Google selectively crawling CRLs, and adding entries with reason codes that Google determines is valuable.  Not including reason codes may impact revocation checking with Chrome.

**Comment by grandamp** [comment]
Hold Instruction/'certificateHold' Reason Code/Suspension

Though I am not entirely up to speed with the public trust baseline, I was informed long ago by @dcooper16 that the EU had requirements to support suspension.  However, this may only pertain to human identity certificates.  In FPKI, there is no stipulation, however it is used often within FPKI with no clarification on suspension intent.  (Identity/Certificate suspension, vs use/key suspension)

**Comment by lachellel** [comment]
For: 

> Issuer Signature
> Match whatever algorithm the issuer CA algorithm uses; we should ask the question if we should specify ECC

Not including ECC in initial draft updates.  **Issuer Signature** algorithms are sha256 WithRSAEncryption {1 2 840 113549 1 1 11} throughout **all** profiles.
