### ISSUE TITLE
IV Certs and CT Logs? 

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#90]
Question for colleagues - 

- Anyone have time to run some queries on the CT logs (and other tools) on how many IV certs are currently logged? 

- **General questions on the table are:** 
  - Policies for CT Log Operators, where anyone "could" submit certificates for inclusion, and the privacy impacts and protections if certs have PII and the subscriber needs to be allowed recourse to request removal of information. OR
  - Policies for CT Log Operators to reject certificates submitted for inclusion which have certain characteristics (IV?)

Impact on USG - how to ensure the **non** Public Trust certificates for **persons** are NOT logged to CT logs.

**Comment by lachellel** [comment]
censys.io
crt.sh

**Comment by grandamp** [comment]
What is an IV cert?

**Comment by lachellel** [comment]
Sorry - Individual Validation cert (I should reference one of your other older posts on IV vs OV vs DV).  

* https://github.com/uspki/policies/blob/master/certificate-policy.md#323-authentication-of-individual-identity

Per the quick reference ~ 30K IV certs come up on censys.io, using CAB Forum IV OID

**Comment by lachellel** [comment]
Closing...this was a CT Log Policy discussion.  Can go into CT Logs - not related to cert policy for now.
