### ISSUE TITLE
Section 7.1.4 - fix markdown

### ISSUE THREAD

**Issue by lachellel** [uspki/policies#91]
markdown for 7.4.x did not translate well 

please fix...

**Comment by konklone** [comment]
Of which document?

**Comment by lachellel** [comment]
good point.  I was rushing to open an issue, so we wouldn't forget to fix it. 

- certificate policy markdown
- policies/certificate-policy.md

**Comment by konklone** [comment]
@lachellel I thought that might be what you meant, but I don't see where an original version (that might have been screwed up in a markdown conversion) of 7.4 is -- it's not in the [PDF](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.4.2.pdf) or [Markdown](https://github.com/cabforum/documents/blob/master/docs/BR.md) version of the BRs.

**Comment by lachellel** [comment]
This was 7.1.4 (fat fingers typing on small screens?)

Fixed in #104
