### ISSUE TITLE
Policy qualifiers - allowed or not?

### ISSUE THREAD

**Issue by dcooper16** [uspki/policies#94]
I was just skimming through the policy and found the following contradictory text. Section 7.1.8 says:
```
7.1.8 Policy qualifiers syntax and semantics

Certificates issued under this CP SHALL NOT contain policy qualifiers.
```
However, Section 7.1.2.3 says that policy qualifiers are optional in subscriber certificates:
```
This extension MUST be present and SHOULD NOT be marked critical.

*   certificatePolicies:policyIdentifier (Required)

    A Policy Identifier, defined by the issuing CA, that indicates a Certificate Policy asserting the issuing CA's adherence to and compliance with these Requirements.

    The following extensions MAY be present:

    *   certificatePolicies:policyQualifiers:policyQualifierId (Recommended)

        *   id-qt 1 [RFC 5280].

    *   certificatePolicies:policyQualifiers:qualifier:cPSuri (Optional)

        HTTP URL for the Subordinate CA's Certification Practice Statement, Relying Party Agreement or other pointer to online information provided by the CA.
```
The profiles for server authentication certificates and OCSP responder certificates also says that policy qualifiers are optional.

Also, while the text in Section 7.1.2.3 was copied from the Baseline Requirements document, it doesn't make sense. A policy qualifier consists of a SEQUENCE of a identifier (indicating the type of qualifier) and a value. A policyQualifierId of "id-qt 1" means that the value will be a pointer to the CPS published by the CA. You can't have a policyQualifierId without having a corresponding value, and in the case that the policyQualifierId is "id-qt 1" the corresponding value is the cPSuri.

So, that means that " certificatePolicies:policyQualifiers:policyQualifierId" and "certificatePolicies:policyQualifiers:qualifier:cPSuri" are **not** different extensions, and it makes no sense to say that one is recommended and the other is optional.

Perhaps more appropriate language would be:
```
A CPS Pointer policy qualifier ( {id-qt 1} ) MAY be present, where the pointer is an  HTTP URL for the Subordinate CA's Certification Practice Statement, Relying Party Agreement or other pointer to online information provided by the CA.
```

**Comment by lachellel** [comment]
@dcooper16 

You are correct for 7.1.8.  It was this commit:  

- https://github.com/uspki/policies/commit/1de3c0cc13123238d6edd801f513e55bee864727

It was after these series of commits that we stepped back and decided to do the profiles first; then go back and update / align, which will require some reversions.

**Comment by lachellel** [comment]
@dcooper16  @techliaison

For 7.1.2.3 - the same verbiage still exists in master for CA/B Forum BRD: 

- https://github.com/cabforum/documents/blob/master/docs/BR.md#7123-subscriber-certificate


1.  Do we have a suggestion to submit to CA/B for the broader community?  

1.  I think we can update this CP to reflect @dcooper16 verbiage, without harming our alignment.  It would clarify the policy for our purposes.

**Comment by lachellel** [comment]
Bump - we need to address @dcooper16  comments and the certificate profiles.

**Comment by lachellel** [comment]
This issue was kept open to ensure comments were addressed. 

- Section 7 details were removed and reference the certificate profiles (Appendix) 
- policy qualifiers are optional
