### ISSUE TITLE
How to integrate CAB Forum Network Security Requirements

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#96]
I know we started with the CAB Forum BRs, but the network security requirements are an additional document that we will be required to implement.

**Comment by lachellel** [comment]
@weirdscience 
Can you link to the network security requirements in this Issue?

**Comment by weirdscience** [comment]
https://cabforum.org/network-security/

**Comment by lachellel** [comment]
@weirdscience 
Do you have a suggestion for best approach for these?  For example, 1) inclusion in the CP by reference, 2) inclusion in the CP by section, 3) inclusion in the CPS template by reference or section? 

There are a few requirements where USG has more stringent requirements.   How should we tailor these to apply? 

For example: 

Item **1.12**: 

> Apply recommended security patches to Certificate Systems within six months of the security patch’s availability, unless the CA documents that the security patch would introduce additional vulnerabilities or instabilities that outweigh the benefits of applying the security patch

  - we have <= 30 days for critical, <= 90 days for high

Item **2.7**: 

> If an authentication control used by a Trusted Role is a username and password, then, where technically feasible, implement the following controls

 - these are in need of update

**Comment by weirdscience** [comment]
Yep, some are already integrated and some may not. @techliaison and I are working on the gap analysis and figure out which fits in what document. We have it in a spreadsheet. Where's the best place to share it?

Open a new page? I was looking at using the 18F Masonry Framework as an ongoing compliance system. Dashboards!! https://18f.gsa.gov/2016/04/15/compliance-masonry-buildling-a-risk-management-platform/

**Comment by lachellel** [comment]
here...all open :+1: 

You can do an attachment

**Comment by weirdscience** [comment]
@konklone any experience with the compliance masonry? Might be good for the NPE root to show trust store compliance. Cloud.gov is using it for their SSP (Security Plan).

Attached are the network security requirements aligned with a CP section.
[CabForumNetworkSecReqs-1-1.xlsx](https://github.com/uspki/policies/files/841736/CabForumNetworkSecReqs-1-1.xlsx)

**Comment by konklone** [comment]
@weirdscience Actually, I don't have any experience with it myself, but I could certainly connect folks to uor staff who do. For the thread's reference, that's what produces https://compliance.cloud.gov (though the final final SSP that got JAB ATO'd did end up diverging from this a bit, we're still in the process of going back and updating this).

**Comment by weirdscience** [comment]
Resolved with #107. I'm closing it.
