### ISSUE TITLE
How to integrate individual trust store requirements

### ISSUE THREAD

**Issue by weirdscience** [uspki/policies#97]
In addition to the CAB Forum BRs and network security requirements each individual trust store has their own set of requirements in addition to the BRs. I have a spread sheet of the individual trust store requirements for Common Policy which we can use for NPE CP development.

**Comment by lachellel** [comment]
@weirdscience: 

One question related to #87 and CRL profile:

> Reason Code
> 
> May be a potential concern because it may deviate from CAB Forum requirements; we need to check if this is CAB forum requirement before we include it, though Para 7.2.2 or 4.9 is empty; **we also need to look at additional requirements that other trust stores may require**

Are there any additional requirements for CRL Reason Code and trust stores?

**Comment by weirdscience** [comment]
Nothing in trust store requirements for CRL reason codes.

**Comment by weirdscience** [comment]
I'm going to create a branch per trust store and open an issue per trust store as well.

**Comment by weirdscience** [comment]
Issue fixed
