### ISSUE TITLE
NSS PKI Wildcard text

### ISSUE THREAD

**Issue by LarryFrank** [uspki/policies#98]
NSS PKI has adopted some specific requirements related to approval of wildcard certificates.  As discussed, these need to be considered in this CP.  Here is the specific wildcard related text.

Section 1.3.6.3 (device subscribers) "System or Device SSL or TLS certificates may contain a wildcard designator (*). These certificates are referred to as wildcard certificates in this CP."

Section 3.1.1  "•	For wildcard certificates, the wildcard designator may be included in the Common Name (CN) or SubjectAltName (SAN) or both"

Section 3.1.2 "Wildcard certificates shall not have the wildcard immediately to the left of an agency or organization name.  The name space of the wildcard certificate shall be specific to restrict the use of the certificate to only the system or set of systems designated for a single application or service."

Section 3.1.5 "Where there is a certificate with a wildcard designator in the CN, the PKI shall not issue any other certificate with a CN that overlaps or is a subset of that name space."

Section 3.2.2 "For specific requirements for verification of wildcard certificates, see Section 3.2.3.3."

Section 3.2.3.3 "For wildcard certificates, the RA shall verify that there is a technical justification that necessitates the use of the wildcard."

Section 3.2.3.3 "For wildcard certificates, the RA shall also verify that the entire wildcard namespace is under the control of the PKI Sponsor"

Section 3.2.3.3 "For wildcard certificates, the PKI Sponsor shall be accountable for all copies of the private key."

Section 3.2.3.3 "For wildcard certificates, the RA Officer shall document approval of the technical justification provided by the PKI Sponsor."

Section 4.5.1 "Each NSS PKI member agency that supports wildcard certificates shall develop internal policies and procedures for determining who can be PKI Sponsors for wildcard certificates, managing wildcard namespaces, and for authorizing PKI Sponsors’ control over these namespaces.  NSS PKI member agencies that issue wildcard certificates to commercial services shall ensure that providers document the management and control mechanisms for the wildcard certificates and associated private keys."

Section 6.3.2 table limits cert and key life for wild card certificates to 1 year.

Added a definition "Wildcard Certificate: A System or Device certificate that contains a wildcard designator (*) in the common name (CN) in the Subject field or in the subjectAltName (SAN) extension."

**Comment by PaulSD** [comment]
The Section 3.1.2 and 3.1.5 language above appears to have been copied from an early revision of the FPKI CAB Forum Baseline Requirements Alignment change proposal.  This language is problematic in a number of subtle ways, and was the subject of some significant FPKI working group discussions.  I would suggest using the language currently listed in Section 3.1.1 of the FCPF cert policy:

- Wildcard Domain Names are permitted if all sub-domains covered by the wildcard fall within the same application, cloud service, or system accreditation boundary within the scope of the sponsoring Agency.  
- Wildcards shall not be used in subdomains that host more than one distinct application platform. The use of third-level Agency wildcards, (e.g., *.[agency].gov), shall be prohibited to reduce the likelihood that a certificate will overlap multiple systems or services.  Third level wildcards are permitted for DNS names dedicated to a specific application (e.g., *.[application_name].gov).  
- Before issuing a publicly trusted serverAuth certificate containing a wildcard, the CA shall ensure the sponsoring agency has a documented procedure for determining that the scope of the certificate does not now and will not infringe on other agency applications.

**Comment by lachellel** [comment]
@PaulSD 

> Before issuing a publicly trusted serverAuth certificate containing a wildcard, the CA shall ensure the sponsoring agency has a documented procedure for determining that the scope of the certificate does not now and will not infringe on other agency applications

How do we do this? Looking towards a small agile infrastructure (issuing CAs and CT logs) and with the hopes that manual processes are reduced as much as possible.  

Just a question.

**Comment by lachellel** [comment]
@LarryFrank 

> Section 6.3.2 table limits cert and key life for wild card certificates to 1 year.

Is this a recommendation?  
Could we align with other dates to keep it simpler?  (13 months with an eye towards the future)

**Comment by LarryFrank** [comment]
> Is this a recommendation?

Section 6.3.2 - I think it could be (should be?) the same as other certs.  I didn't see a good reason for making it 1 year when they did that...

**Comment by LarryFrank** [comment]
> How do we do this? Looking towards a small agile infrastructure (issuing CAs and CT logs) and with the hopes that manual processes are reduced as much as possible.

Frankly, I don't see anyway to use an automated process to approve issuance of a wild card certificate given all the specific constraints that have to be applied - most of which can not be done (in any way obvious to me) automatically.

**Comment by techliaison** [comment]
agree with wildcard certs needing a more manual approval process.
If we can reach agreement on the use of some sort of revalidation based on authorized digital signature that nothing has changed in the organizational control of the site for rekey - re-issuance after the first one may be more automated in a similar fashion to non-wildcard.

**Comment by LarryFrank** [comment]
Current BR has "no stipulation" for rekey - which means we can specify what is typically done - use the current cert to authenticate for a new one.  That would (in my opinion) be equally applicable for wildcards.  Typically, rekey is limited to a certain time frame - after which, an "initial issuance process" needs to be followed.   Common/FBCA Medium allows up to 9 years - so could do an initial issuance and 8 1-year rekeys before  back to whatever is required for "initial."

**Comment by lachellel** [comment]
Wildcard discussion - some notes: 

- For this CP covering DotGov and DotMil gTLDs: explicitly prohibit wildcards covering the entire gTLD, even though it is allowed by baseline requirements
- adopt modified policy statements from NSS and Common
- broad dotgov and dotmil policy for use of wildcards should / could be addressed govt wide; the CP should not attempt to indirectly create a policy that is not specific to the issuing infrastructure
-
